package query

import (
	"encoding/json"
	"fmt"
	"os"
)

// LoadMetadata reads and parses the query metadata JSON file
func LoadMetadata(path string) (*QueryMetadata, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read metadata file: %w", err)
	}

	var metadata QueryMetadata
	if err := json.Unmarshal(data, &metadata); err != nil {
		return nil, fmt.Errorf("failed to parse metadata: %w", err)
	}

	return &metadata, nil
}

// QueryMetadata represents the complete structure generated by sqlc plugin
type QueryMetadata struct {
	Queries       []Query `json:"queries"`
	Enums         []Enum  `json:"enums"`
	DefaultSchema string  `json:"default_schema"`
}

// Enum describes an enum type from the database catalog
type Enum struct {
	Schema string   `json:"schema"`
	Name   string   `json:"name"`
	Vals   []string `json:"vals"`
}

// FindEnum looks up the enum definition for a type reference, returning nil if
// the type is not a known enum. Unqualified references resolve against the
// catalog's default schema, so two same-named enums in different schemas
// cannot be confused.
func (m *QueryMetadata) FindEnum(t TypeRef) *Enum {
	schema := t.Schema
	if schema == "" {
		schema = m.DefaultSchema
	}
	for i := range m.Enums {
		e := &m.Enums[i]
		enumSchema := e.Schema
		if enumSchema == "" {
			enumSchema = m.DefaultSchema
		}
		if e.Name == t.Name && enumSchema == schema {
			return e
		}
	}
	return nil
}

// Query represents a single SQL query with its metadata
type Query struct {
	Text     string   `json:"text"`
	Name     string   `json:"name"`
	Cmd      string   `json:"cmd"` // :one, :many, :exec
	Columns  []Column `json:"columns"`
	Params   []Param  `json:"params"`
	Comments []string `json:"comments"`
	Filename string   `json:"filename"`

	// Classification is not part of the plugin's metadata; it is filled in
	// after loading by ClassifyQueries, and is nil when the query could not
	// be classified.
	Classification *Classification `json:"-"`
}

// Column represents a column in the query result
type Column struct {
	Name         string   `json:"name"`
	NotNull      bool     `json:"not_null"`
	IsArray      bool     `json:"is_array"`
	Comment      string   `json:"comment"`
	Length       int      `json:"length"`
	IsNamedParam bool     `json:"is_named_param"`
	IsFuncCall   bool     `json:"is_func_call"`
	Scope        string   `json:"scope"`
	Table        TableRef `json:"table"`
	TableAlias   string   `json:"table_alias"`
	Type         TypeRef  `json:"type"`
	IsSQLCSlice  bool     `json:"is_sqlc_slice"`
	EmbedTable   any      `json:"embed_table"`
	OriginalName string   `json:"original_name"`
	Unsigned     bool     `json:"unsigned"`
	ArrayDims    int      `json:"array_dims"`
}

// Param represents a query parameter
type Param struct {
	Number int    `json:"number"`
	Column Column `json:"column"`
}

// TableRef represents a table reference
type TableRef struct {
	Catalog string `json:"catalog"`
	Schema  string `json:"schema"`
	Name    string `json:"name"`
}

// TypeRef represents a type reference
type TypeRef struct {
	Catalog string `json:"catalog"`
	Schema  string `json:"schema"`
	Name    string `json:"name"`
}
