// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AuthInfoType.
const (
	AuthInfoTypeApiKey AuthInfoType = "api_key"
	AuthInfoTypeUser   AuthInfoType = "user"
)

// Defines values for DatabaseSize.
const (
	DatabaseSizeN1x DatabaseSize = "1x"
	DatabaseSizeN2x DatabaseSize = "2x"
	DatabaseSizeN4x DatabaseSize = "4x"
	DatabaseSizeN8x DatabaseSize = "8x"
)

// Defines values for DatabaseStatus.
const (
	DatabaseStatusConfiguring DatabaseStatus = "configuring"
	DatabaseStatusDeleted     DatabaseStatus = "deleted"
	DatabaseStatusDeleting    DatabaseStatus = "deleting"
	DatabaseStatusPaused      DatabaseStatus = "paused"
	DatabaseStatusPausing     DatabaseStatus = "pausing"
	DatabaseStatusQueued      DatabaseStatus = "queued"
	DatabaseStatusResuming    DatabaseStatus = "resuming"
	DatabaseStatusRunning     DatabaseStatus = "running"
	DatabaseStatusUnknown     DatabaseStatus = "unknown"
	DatabaseStatusUnstable    DatabaseStatus = "unstable"
	DatabaseStatusUpgrading   DatabaseStatus = "upgrading"
)

// Defines values for DatabaseType.
const (
	DatabaseTypeDedicated DatabaseType = "dedicated"
	DatabaseTypeStandard  DatabaseType = "standard"
)

// Defines values for InvoiceStatus.
const (
	InvoiceStatusDelinquent InvoiceStatus = "delinquent"
	InvoiceStatusIssued     InvoiceStatus = "issued"
	InvoiceStatusPaid       InvoiceStatus = "paid"
)

// ApiKey An API key in a space.
type ApiKey struct {
	// CreatedAt Time the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Name User-provided label for the API key.
	Name string `json:"name"`

	// Prefix Stable prefix identifier for the API key (starts with `gt_`), identifying the key without exposing the secret.
	Prefix string `json:"prefix"`
}

// ApiKeyCredentials Credentials for a newly created API key. The secret portion cannot be retrieved again later.
type ApiKeyCredentials struct {
	// AccessKey Use as the username in HTTP Basic auth.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AccessKey string `json:"access_key"`

	// ApiKey Bearer token for the key. Use as `Authorization: Bearer <api_key>`.
	ApiKey string `json:"api_key"`

	// SecretKey Use as the password in HTTP Basic auth.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SecretKey string `json:"secret_key"`
}

// ApiKeyInfo Information about the API key used for authentication.
type ApiKeyInfo struct {
	// CreatedAt Time the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Name User-provided label for the API key.
	Name string `json:"name"`

	// Prefix Stable prefix identifier for the API key (starts with `gt_`), identifying the key without exposing the secret.
	Prefix string `json:"prefix"`

	// SpaceId Space the API key is scoped to.
	SpaceId string `json:"space_id"`

	// SpaceName Name of the space the API key is scoped to.
	SpaceName string `json:"space_name"`

	// UserEmail Email of the user who created the API key.
	UserEmail string `json:"user_email"`

	// UserId ID of the user who created the API key.
	UserId string `json:"user_id"`

	// UserName Name of the user who created the API key.
	UserName string `json:"user_name"`
}

// AuthInfo Information about the authenticated caller.
type AuthInfo struct {
	// ApiKey Information about the API key used for authentication.
	ApiKey *ApiKeyInfo `json:"api_key,omitempty"`

	// Type Type of authentication used.
	Type AuthInfoType `json:"type"`

	// User Authenticated user details.
	User *UserInfo `json:"user,omitempty"`
}

// AuthInfoType Type of authentication used.
type AuthInfoType string

// ComputePrice Compute price for one size.
type ComputePrice struct {
	// MemoryGib Memory allocation in GiB.
	MemoryGib int `json:"memory_gib"`

	// MilliCpu CPU allocation in millicores (1000 = 1 vCPU).
	MilliCpu int `json:"milli_cpu"`

	// PricePerHour Price per hour while the database is running.
	PricePerHour float64 `json:"price_per_hour"`

	// PricePerMonth Price per month while the database is running.
	PricePerMonth float64 `json:"price_per_month"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size DatabaseSize `json:"size"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// Name User-provided label for the new API key.
	Name string `json:"name"`
}

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	// Name Name for the new database. Auto-generated if omitted.
	Name *string `json:"name,omitempty"`

	// ShareToken Share token from a database share (begins with `gs_`). When provided, creates the new database from the shared snapshot.
	ShareToken *string `json:"share_token,omitempty"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type *DatabaseType `json:"type,omitempty"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	// Name Name for the new space.
	Name string `json:"name"`
}

// Database A Ghost database.
type Database struct {
	// Host PostgreSQL hostname for connections.
	Host string `json:"host"`

	// Id Database ID.
	Id string `json:"id"`

	// Name Database name. Unique within the space.
	Name string `json:"name"`

	// Password PostgreSQL password for the default user. Returned on every GET for authorized callers.
	Password *string `json:"password"`

	// Port PostgreSQL port for connections.
	Port int `json:"port"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Status Current lifecycle status of the database.
	Status DatabaseStatus `json:"status"`

	// StorageMib Current disk usage in MiB. Null if not yet available.
	StorageMib *int `json:"storage_mib"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type DatabaseType `json:"type"`
}

// DatabaseShare A shareable snapshot of a database. Can be used to create a new database from the snapshot in another space.
type DatabaseShare struct {
	// CreatedAt Time the share was created.
	CreatedAt time.Time `json:"created_at"`

	// DatabaseId ID of the source database.
	DatabaseId string `json:"database_id"`

	// DatabaseName Name of the source database.
	DatabaseName string `json:"database_name"`

	// ExpiresAt Time the share expires. Absent if the share does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// RevokedAt Time the share was revoked. Absent if the share is still active.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`

	// ShareToken Token passed to `createDatabase` (via `share_token`) to create a new database from the shared snapshot in another space. Also used to revoke the share via `revokeShare`. Always begins with `gs_`.
	ShareToken string `json:"share_token"`
}

// DatabaseSize Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
type DatabaseSize string

// DatabaseStatus Current lifecycle status of the database.
type DatabaseStatus string

// DatabaseType Database deployment model.
// - `standard` — shared-resource databases subject to the space's compute and storage limits.
// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
type DatabaseType string

// DatabaseWithUsage defines model for DatabaseWithUsage.
type DatabaseWithUsage struct {
	// ComputeMinutes Compute minutes used by this database during the current billing cycle. Only populated for `standard` databases.
	ComputeMinutes *int64 `json:"compute_minutes"`

	// Host PostgreSQL hostname for connections.
	Host string `json:"host"`

	// Id Database ID.
	Id string `json:"id"`

	// Name Database name. Unique within the space.
	Name string `json:"name"`

	// Password PostgreSQL password for the default user. Returned on every GET for authorized callers.
	Password *string `json:"password"`

	// Port PostgreSQL port for connections.
	Port int `json:"port"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Status Current lifecycle status of the database.
	Status DatabaseStatus `json:"status"`

	// StorageMib Current disk usage in MiB. Null if not yet available.
	StorageMib *int `json:"storage_mib"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type DatabaseType `json:"type"`
}

// DedicatedPricing Pricing for dedicated databases.
type DedicatedPricing struct {
	// Compute Per-size compute pricing, ordered smallest to largest.
	Compute []ComputePrice `json:"compute"`

	// Storage Storage pricing.
	Storage StoragePrice `json:"storage"`
}

// Error Standard error response.
type Error struct {
	// Message Human-readable error message.
	Message string `json:"message"`
}

// FeedbackRequest User-submitted feedback or bug report.
type FeedbackRequest struct {
	// Message Feedback message from the user.
	Message string `json:"message"`

	// Os Operating system of the client submitting the feedback.
	Os string `json:"os"`

	// Source Source of the feedback request (e.g. `cli`, `mcp`).
	Source string `json:"source"`

	// Version Version of the client submitting the feedback.
	Version string `json:"version"`
}

// ForkDatabaseRequest Request body for forking a database. Fields default to the source database's values when omitted.
type ForkDatabaseRequest struct {
	// Name Name for the forked database. Auto-generated from the source name if omitted.
	Name *string `json:"name,omitempty"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type *DatabaseType `json:"type,omitempty"`
}

// IdentifyRequest User properties to associate with the authenticated user in analytics.
type IdentifyRequest struct {
	// Properties Free-form user properties.
	Properties map[string]interface{} `json:"properties"`
}

// Invoice Invoice summary.
type Invoice struct {
	// Id Opaque invoice ID used to look up invoice details.
	Id string `json:"id"`

	// InvoiceDate Date the invoice was issued.
	InvoiceDate time.Time `json:"invoice_date"`

	// InvoiceNumber Human-readable invoice number (e.g. "INV-12345").
	InvoiceNumber string `json:"invoice_number"`

	// Status Invoice status:
	// - `paid` — invoice has been paid.
	// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
	// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
	Status InvoiceStatus `json:"status"`

	// Total Invoice total.
	Total float64 `json:"total"`
}

// InvoiceStatus Invoice status:
// - `paid` — invoice has been paid.
// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
type InvoiceStatus string

// InvoiceDetail Line-item breakdown of an invoice.
type InvoiceDetail struct {
	// LineItems Line items that make up the invoice.
	LineItems []InvoiceLineItem `json:"line_items"`
}

// InvoiceLineItem defines model for InvoiceLineItem.
type InvoiceLineItem struct {
	// DatabaseId Ghost database ID this line item is attributed to, if any.
	DatabaseId *string `json:"database_id,omitempty"`

	// DetailedSpec Additional spec details (e.g. tier, size).
	DetailedSpec *string `json:"detailed_spec,omitempty"`

	// LineTotal Total charge for this line (`quantity` × `unit_price`).
	LineTotal float64 `json:"line_total"`

	// ProductType Product category (e.g. storage, compute).
	ProductType string `json:"product_type"`

	// Quantity Quantity billed. Units depend on `product_type`.
	Quantity float64 `json:"quantity"`

	// UnitPrice Price per unit of `quantity`.
	UnitPrice float64 `json:"unit_price"`
}

// InvoicesResponse defines model for InvoicesResponse.
type InvoicesResponse struct {
	// Invoices Recent invoices, most recent first.
	Invoices []Invoice `json:"invoices"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Message Log message text
	Message string `json:"message"`

	// Severity PostgreSQL severity level (e.g. LOG, WARNING, ERROR, FATAL)
	Severity string `json:"severity"`

	// Timestamp Timestamp of the log entry (RFC3339 format, with nanosecond precision)
	Timestamp time.Time `json:"timestamp"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken Refresh token to revoke.
	RefreshToken string `json:"refreshToken"`
}

// LogsResponse defines model for LogsResponse.
type LogsResponse struct {
	// Entries Log entries, most recent first.
	Entries []LogEntry `json:"entries"`

	// LastCursor Opaque cursor for the next page of results. Present when more log
	// entries exist older than the last entry in this response. Pass
	// this value as the `cursor` query parameter to retrieve the next
	// page. Absent when there are no further results.
	LastCursor *string `json:"last_cursor,omitempty"`
}

// PaymentMethod A payment method on file for a space.
type PaymentMethod struct {
	// Brand Card brand (e.g. `visa`, `mastercard`).
	Brand string `json:"brand"`

	// ExpMonth Card expiration month (1-12).
	ExpMonth int `json:"exp_month"`

	// ExpYear Card expiration year (four digits).
	ExpYear int `json:"exp_year"`

	// Id Payment method ID.
	Id string `json:"id"`

	// Last4 Last four digits of the card number.
	Last4 string `json:"last4"`

	// PendingDeletion True if deletion has been scheduled for this payment method. The deletion can be cancelled until processed.
	PendingDeletion bool `json:"pending_deletion"`

	// Primary True if this is the primary payment method for the space.
	Primary bool `json:"primary"`
}

// PaymentMethodsResponse defines model for PaymentMethodsResponse.
type PaymentMethodsResponse struct {
	// PaymentMethods Payment methods on file for the space.
	PaymentMethods []PaymentMethod `json:"payment_methods"`
}

// PaymentSetupResponse Stripe Setup Intent details for collecting a new payment method.
type PaymentSetupResponse struct {
	// ClientSecret Stripe Setup Intent client secret.
	ClientSecret string `json:"client_secret"`

	// PaymentUrl URL of the hosted payment page for collecting card details.
	PaymentUrl string `json:"payment_url"`
}

// Pricing Pricing data grouped by category.
type Pricing struct {
	// Dedicated Pricing for dedicated databases.
	Dedicated DedicatedPricing `json:"dedicated"`

	// Standard Pricing for standard (non-dedicated) databases, which share a
	// space-wide compute allowance.
	Standard StandardPricing `json:"standard"`
}

// RenameDatabaseRequest defines model for RenameDatabaseRequest.
type RenameDatabaseRequest struct {
	// Name New name for the database.
	Name string `json:"name"`
}

// ShareDatabaseRequest Options for creating a database share.
type ShareDatabaseRequest struct {
	// ExpiresAt Time after which the share expires. If omitted, the share does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// Space A Ghost space.
type Space struct {
	// Id Space ID.
	Id string `json:"id"`

	// Name Space name.
	Name string `json:"name"`
}

// SpaceUsage Space-level usage and cost for the current billing cycle.
type SpaceUsage struct {
	// BillingPeriodEnd End of the current billing cycle.
	BillingPeriodEnd *time.Time `json:"billing_period_end,omitempty"`

	// BillingPeriodStart Start of the current billing cycle.
	BillingPeriodStart *time.Time `json:"billing_period_start,omitempty"`

	// ComputeLimitMinutes Compute-minute quota for the space. When exceeded, all standard
	// databases in the space are automatically paused. `null` means no
	// limit — only possible when `overages_enabled` is true.
	ComputeLimitMinutes *int64 `json:"compute_limit_minutes"`

	// ComputeMinutes Total compute minutes used across all databases in the space during the current billing cycle.
	ComputeMinutes int64 `json:"compute_minutes"`

	// CostToDate Gross cost accrued so far this billing cycle.
	CostToDate *float64 `json:"cost_to_date,omitempty"`

	// EstimatedTotalCost Projected gross total for the current billing cycle based on usage to date.
	EstimatedTotalCost *float64 `json:"estimated_total_cost,omitempty"`

	// FreeComputeMinutes Compute minutes included per billing cycle at no additional charge,
	// shared across all standard databases in the space. Usage beyond this
	// is billed only when `overages_enabled` is true.
	FreeComputeMinutes int64 `json:"free_compute_minutes"`

	// OveragesEnabled Whether the space has compute overages enabled.
	OveragesEnabled bool `json:"overages_enabled"`

	// StorageLimitMib Storage quota for the space, in MiB.
	StorageLimitMib int64 `json:"storage_limit_mib"`

	// StorageMib Total storage used across all databases in the space, in MiB.
	StorageMib int64 `json:"storage_mib"`
}

// StandardComputePrice Pricing for standard (shared) compute used beyond the free monthly
// allowance.
type StandardComputePrice struct {
	// IncludedComputeHoursPerMonth Compute-hours included per month at no additional charge, shared
	// across all standard databases in the space. Only usage above this
	// amount is billed at `price_per_hour`.
	IncludedComputeHoursPerMonth int `json:"included_compute_hours_per_month"`

	// PricePerHour Price per compute-hour used beyond the included monthly allowance,
	// metered in 15-minute increments.
	PricePerHour float64 `json:"price_per_hour"`
}

// StandardPricing Pricing for standard (non-dedicated) databases, which share a
// space-wide compute allowance.
type StandardPricing struct {
	// Compute Pricing for standard (shared) compute used beyond the free monthly
	// allowance.
	Compute StandardComputePrice `json:"compute"`
}

// StatusResponse Generic success response.
type StatusResponse struct {
	// Status Status string (e.g. `success`).
	Status string `json:"status"`
}

// StoragePrice Storage pricing.
type StoragePrice struct {
	// IncludedGibPerDatabase GiB of storage included per database at no additional charge. Only
	// storage above this amount is billed at `price_per_gib_hour`.
	IncludedGibPerDatabase int `json:"included_gib_per_database"`

	// PricePerGibHour Price per GiB per hour of provisioned storage above the included amount.
	PricePerGibHour float64 `json:"price_per_gib_hour"`

	// PricePerGibMonth Price per GiB per month of provisioned storage above the included amount.
	PricePerGibMonth float64 `json:"price_per_gib_month"`
}

// TrackRequest An analytics event to record.
type TrackRequest struct {
	// Event Event name.
	Event string `json:"event"`

	// Properties Free-form event properties.
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// UpdateOverageSettingsRequest Request body for updating compute overage settings on a space.
type UpdateOverageSettingsRequest struct {
	// ComputeLimitMinutes Optional when `enabled` is true: the monthly compute-minute limit
	// above which standard databases auto-pause. Must be greater than
	// the free-tier limit (6000 minutes). Omit or set to `null` for no
	// limit — the user is billed for all overage usage with no upper
	// bound. Must be omitted (or `null`) when `enabled` is false; on
	// disable the server resets the limit to the free-tier default.
	ComputeLimitMinutes *int64 `json:"compute_limit_minutes"`

	// Enabled Set to true to enable overages, false to disable.
	Enabled bool `json:"enabled"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	// Password New PostgreSQL password for the default user.
	Password string `json:"password"`
}

// UserInfo Authenticated user details.
type UserInfo struct {
	// Email User email address.
	Email string `json:"email"`

	// Id User ID.
	Id string `json:"id"`

	// Name User's full name.
	Name string `json:"name"`
}

// ApiKeyPrefix defines model for ApiKeyPrefix.
type ApiKeyPrefix = string

// DatabaseRef defines model for DatabaseRef.
type DatabaseRef = string

// PaymentId defines model for PaymentId.
type PaymentId = string

// SpaceId defines model for SpaceId.
type SpaceId = string

// DatabaseLogsParams defines parameters for DatabaseLogs.
type DatabaseLogsParams struct {
	// Cursor Opaque pagination cursor returned as `last_cursor` in a previous
	// response. When provided, returns the next page of logs older than
	// the cursor position.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Until Upper bound timestamp — return logs at or before this time (RFC3339 format, e.g., 2024-01-15T10:00:00Z). Defaults to now.
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`

	// Since Lower bound timestamp — fetch logs after this time (RFC3339 format, e.g., 2024-01-15T09:00:00Z)
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Search Full-text search terms to filter log lines. Repeat the parameter
	// for multiple values (e.g. `?search=slow+query&search=ERROR`).
	Search *[]string `form:"search,omitempty" json:"search,omitempty"`

	// Severity Severity levels to filter results. Repeat the parameter for multiple
	// values (e.g. `?severity=ERROR&severity=WARNING`). Common values
	// include `LOG`, `WARNING`, `ERROR`, and `FATAL`; PostgreSQL may also
	// emit `DEBUG*`, `INFO`, `NOTICE`, and `PANIC`.
	Severity *[]string `form:"severity,omitempty" json:"severity,omitempty"`
}

// AnalyticsIdentifyJSONRequestBody defines body for AnalyticsIdentify for application/json ContentType.
type AnalyticsIdentifyJSONRequestBody = IdentifyRequest

// AnalyticsTrackJSONRequestBody defines body for AnalyticsTrack for application/json ContentType.
type AnalyticsTrackJSONRequestBody = TrackRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = FeedbackRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// ForkDatabaseJSONRequestBody defines body for ForkDatabase for application/json ContentType.
type ForkDatabaseJSONRequestBody = ForkDatabaseRequest

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UpdatePasswordRequest

// RenameDatabaseJSONRequestBody defines body for RenameDatabase for application/json ContentType.
type RenameDatabaseJSONRequestBody = RenameDatabaseRequest

// ShareDatabaseJSONRequestBody defines body for ShareDatabase for application/json ContentType.
type ShareDatabaseJSONRequestBody = ShareDatabaseRequest

// UpdateOveragesJSONRequestBody defines body for UpdateOverages for application/json ContentType.
type UpdateOveragesJSONRequestBody = UpdateOverageSettingsRequest
