// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AuthInfoType.
const (
	AuthInfoTypeAPIKey AuthInfoType = "api_key"
	AuthInfoTypeUser   AuthInfoType = "user"
)

// Valid indicates whether the value is a known member of the AuthInfoType enum.
func (e AuthInfoType) Valid() bool {
	switch e {
	case AuthInfoTypeAPIKey:
		return true
	case AuthInfoTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseSize.
const (
	DatabaseSizeN1X DatabaseSize = "1x"
	DatabaseSizeN2X DatabaseSize = "2x"
	DatabaseSizeN4X DatabaseSize = "4x"
	DatabaseSizeN8X DatabaseSize = "8x"
)

// Valid indicates whether the value is a known member of the DatabaseSize enum.
func (e DatabaseSize) Valid() bool {
	switch e {
	case DatabaseSizeN1X:
		return true
	case DatabaseSizeN2X:
		return true
	case DatabaseSizeN4X:
		return true
	case DatabaseSizeN8X:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatus.
const (
	DatabaseStatusConfiguring DatabaseStatus = "configuring"
	DatabaseStatusDeleted     DatabaseStatus = "deleted"
	DatabaseStatusDeleting    DatabaseStatus = "deleting"
	DatabaseStatusPaused      DatabaseStatus = "paused"
	DatabaseStatusPausing     DatabaseStatus = "pausing"
	DatabaseStatusQueued      DatabaseStatus = "queued"
	DatabaseStatusResuming    DatabaseStatus = "resuming"
	DatabaseStatusRunning     DatabaseStatus = "running"
	DatabaseStatusUnknown     DatabaseStatus = "unknown"
	DatabaseStatusUnstable    DatabaseStatus = "unstable"
	DatabaseStatusUpgrading   DatabaseStatus = "upgrading"
)

// Valid indicates whether the value is a known member of the DatabaseStatus enum.
func (e DatabaseStatus) Valid() bool {
	switch e {
	case DatabaseStatusConfiguring:
		return true
	case DatabaseStatusDeleted:
		return true
	case DatabaseStatusDeleting:
		return true
	case DatabaseStatusPaused:
		return true
	case DatabaseStatusPausing:
		return true
	case DatabaseStatusQueued:
		return true
	case DatabaseStatusResuming:
		return true
	case DatabaseStatusRunning:
		return true
	case DatabaseStatusUnknown:
		return true
	case DatabaseStatusUnstable:
		return true
	case DatabaseStatusUpgrading:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseType.
const (
	DatabaseTypeDedicated DatabaseType = "dedicated"
	DatabaseTypeStandard  DatabaseType = "standard"
)

// Valid indicates whether the value is a known member of the DatabaseType enum.
func (e DatabaseType) Valid() bool {
	switch e {
	case DatabaseTypeDedicated:
		return true
	case DatabaseTypeStandard:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeComputeLimitExceeded ErrorCode = "compute_limit_exceeded"
	ErrorCodeNoPaymentMethod      ErrorCode = "no_payment_method"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeComputeLimitExceeded:
		return true
	case ErrorCodeNoPaymentMethod:
		return true
	default:
		return false
	}
}

// Defines values for InviteStatus.
const (
	InviteStatusDeclined InviteStatus = "declined"
	InviteStatusPending  InviteStatus = "pending"
)

// Valid indicates whether the value is a known member of the InviteStatus enum.
func (e InviteStatus) Valid() bool {
	switch e {
	case InviteStatusDeclined:
		return true
	case InviteStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for InvoiceStatus.
const (
	InvoiceStatusDelinquent InvoiceStatus = "delinquent"
	InvoiceStatusIssued     InvoiceStatus = "issued"
	InvoiceStatusPaid       InvoiceStatus = "paid"
)

// Valid indicates whether the value is a known member of the InvoiceStatus enum.
func (e InvoiceStatus) Valid() bool {
	switch e {
	case InvoiceStatusDelinquent:
		return true
	case InvoiceStatusIssued:
		return true
	case InvoiceStatusPaid:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleDeveloper MemberRole = "developer"
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleViewer    MemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleAdmin:
		return true
	case MemberRoleDeveloper:
		return true
	case MemberRoleOwner:
		return true
	case MemberRoleViewer:
		return true
	default:
		return false
	}
}

// APIKey An API key in a space.
type APIKey struct {
	// CreatedAt Time the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Name User-provided label for the API key.
	Name string `json:"name"`

	// Prefix Stable prefix identifier for the API key (starts with `gt_`), identifying the key without exposing the secret.
	Prefix string `json:"prefix"`
}

// APIKeyCredentials Credentials for a newly created API key. The secret portion cannot be retrieved again later.
type APIKeyCredentials struct {
	// AccessKey Use as the username in HTTP Basic auth.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AccessKey string `json:"access_key"`

	// APIKey Bearer token for the key. Use as `Authorization: Bearer <api_key>`.
	APIKey string `json:"api_key"`

	// SecretKey Use as the password in HTTP Basic auth.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SecretKey string `json:"secret_key"`
}

// APIKeyInfo Information about the API key used for authentication.
type APIKeyInfo struct {
	// CreatedAt Time the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Name User-provided label for the API key.
	Name string `json:"name"`

	// Prefix Stable prefix identifier for the API key (starts with `gt_`), identifying the key without exposing the secret.
	Prefix string `json:"prefix"`

	// SpaceID Space the API key is scoped to.
	SpaceID string `json:"space_id"`

	// SpaceName Name of the space the API key is scoped to.
	SpaceName string `json:"space_name"`

	// UserEmail Email of the user who created the API key.
	UserEmail string `json:"user_email"`

	// UserID ID of the user who created the API key.
	UserID string `json:"user_id"`

	// UserName Name of the user who created the API key.
	UserName string `json:"user_name"`
}

// AuthInfo Information about the authenticated caller.
type AuthInfo struct {
	// APIKey Information about the API key used for authentication.
	APIKey *APIKeyInfo `json:"api_key,omitempty"`

	// Type Type of authentication used.
	Type AuthInfoType `json:"type"`

	// User Authenticated user details.
	User *UserInfo `json:"user,omitempty"`
}

// AuthInfoType Type of authentication used.
type AuthInfoType string

// ComputePrice Compute price for one size.
type ComputePrice struct {
	// MemoryGib Memory allocation in GiB.
	MemoryGib int `json:"memory_gib"`

	// MilliCPU CPU allocation in millicores (1000 = 1 vCPU).
	MilliCPU int `json:"milli_cpu"`

	// PricePerHour Price per hour while the database is running.
	PricePerHour float64 `json:"price_per_hour"`

	// PricePerMonth Price per month while the database is running.
	PricePerMonth float64 `json:"price_per_month"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size DatabaseSize `json:"size"`
}

// CreateAPIKeyRequest Request to create a new API key in a space.
type CreateAPIKeyRequest struct {
	// Name User-provided label for the new API key.
	Name string `json:"name"`
}

// CreateDatabaseRequest Request to create a new database in a space.
type CreateDatabaseRequest struct {
	// Name Name for the new database. Auto-generated if omitted.
	Name *string `json:"name,omitempty"`

	// ShareToken Share token from a database share (begins with `gs_`). When provided, creates the new database from the shared snapshot.
	ShareToken *string `json:"share_token,omitempty"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type *DatabaseType `json:"type,omitempty"`
}

// CreateInviteRequest Request to invite a user to a space.
type CreateInviteRequest struct {
	// Email Email address to invite.
	Email string `json:"email"`

	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role *MemberRole `json:"role,omitempty"`
}

// CreateSpaceRequest Request to create a new space.
type CreateSpaceRequest struct {
	// Name Name for the new space. When omitted, the space is named after its owner (e.g. "Jane Doe's space").
	Name *string `json:"name,omitempty"`
}

// Database A Ghost database.
type Database struct {
	// Host PostgreSQL hostname for connections.
	Host string `json:"host"`

	// ID Database ID.
	ID string `json:"id"`

	// Name Database name. Unique within the space.
	Name string `json:"name"`

	// Password PostgreSQL password for the default user. Returned on every GET for authorized callers.
	Password *string `json:"password,omitempty"`

	// Port PostgreSQL port for connections.
	Port int `json:"port"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Status Current lifecycle status of the database.
	Status DatabaseStatus `json:"status"`

	// StorageMib Current disk usage in MiB. Null if not yet available.
	StorageMib *int64 `json:"storage_mib,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type DatabaseType `json:"type"`
}

// DatabaseShare A shareable snapshot of a database. Can be used to create a new database from the snapshot in another space.
type DatabaseShare struct {
	// CreatedAt Time the share was created.
	CreatedAt time.Time `json:"created_at"`

	// DatabaseID ID of the source database.
	DatabaseID string `json:"database_id"`

	// DatabaseName Name of the source database.
	DatabaseName string `json:"database_name"`

	// ExpiresAt Time the share expires. Absent if the share does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// RevokedAt Time the share was revoked. Absent if the share is still active.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`

	// ShareToken Token passed to `createDatabase` (via `share_token`) to create a new database from the shared snapshot in another space. Also used to revoke the share via `revokeShare`. Always begins with `gs_`.
	ShareToken string `json:"share_token"`
}

// DatabaseSize Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
type DatabaseSize string

// DatabaseStatus Current lifecycle status of the database.
type DatabaseStatus string

// DatabaseType Database deployment model.
// - `standard` — shared-resource databases subject to the space's compute and storage limits.
// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
type DatabaseType string

// DatabaseWithUsage A Ghost database with current billing-cycle usage included.
type DatabaseWithUsage struct {
	// ComputeMinutes Compute minutes used by this database during the current billing cycle. Only populated for `standard` databases.
	ComputeMinutes *int64 `json:"compute_minutes,omitempty"`

	// Host PostgreSQL hostname for connections.
	Host string `json:"host"`

	// ID Database ID.
	ID string `json:"id"`

	// Name Database name. Unique within the space.
	Name string `json:"name"`

	// Password PostgreSQL password for the default user. Returned on every GET for authorized callers.
	Password *string `json:"password,omitempty"`

	// Port PostgreSQL port for connections.
	Port int `json:"port"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Status Current lifecycle status of the database.
	Status DatabaseStatus `json:"status"`

	// StorageMib Current disk usage in MiB. Null if not yet available.
	StorageMib *int64 `json:"storage_mib,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type DatabaseType `json:"type"`
}

// DedicatedPricing Pricing for dedicated databases.
type DedicatedPricing struct {
	// Compute Per-size compute pricing, ordered smallest to largest.
	Compute []ComputePrice `json:"compute"`

	// Storage Storage pricing.
	Storage StoragePrice `json:"storage"`
}

// Error Standard error response.
type Error struct {
	// Code Machine-readable error code identifying a specific, client-actionable
	// error condition. Clients can match on this to react to specific errors
	// without parsing the human-readable message. Errors without a recognized
	// code omit this field.
	Code *ErrorCode `json:"code,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ErrorCode Machine-readable error code identifying a specific, client-actionable
// error condition. Clients can match on this to react to specific errors
// without parsing the human-readable message. Errors without a recognized
// code omit this field.
type ErrorCode string

// FeedbackRequest User-submitted feedback or bug report.
type FeedbackRequest struct {
	// Message Feedback message from the user.
	Message string `json:"message"`

	// Os Operating system of the client submitting the feedback.
	Os string `json:"os"`

	// Source Source of the feedback request (e.g. `cli`, `mcp`).
	Source string `json:"source"`

	// Version Version of the client submitting the feedback.
	Version string `json:"version"`
}

// ForkDatabaseRequest Request body for forking a database. Fields default to the source database's values when omitted.
type ForkDatabaseRequest struct {
	// Name Name for the forked database. Auto-generated from the source name if omitted.
	Name *string `json:"name,omitempty"`

	// Size Compute size for dedicated databases. Each step up allocates proportionally more vCPU and RAM.
	Size *DatabaseSize `json:"size,omitempty"`

	// Type Database deployment model.
	// - `standard` — shared-resource databases subject to the space's compute and storage limits.
	// - `dedicated` — per-instance paid databases with guaranteed resources, exempt from space-level auto-pause.
	Type *DatabaseType `json:"type,omitempty"`
}

// IdentifyRequest User properties to associate with the authenticated user in analytics.
type IdentifyRequest struct {
	// Properties Free-form user properties.
	Properties map[string]interface{} `json:"properties"`
}

// Invite An invite sent for a space.
type Invite struct {
	// CreatedAt When the invite was created.
	CreatedAt time.Time `json:"created_at"`

	// Email Email address the invite was sent to.
	Email string `json:"email"`

	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role MemberRole `json:"role"`

	// Status Status of a sent invite. `pending` means it's still awaiting a
	// response; `declined` means the invitee declined it. A declined invite
	// still occupies the email's slot for the space (one pending-or-declined
	// invite per email), so it must be cancelled before that email can be
	// re-invited.
	Status InviteStatus `json:"status"`
}

// InviteActionResult Result of accepting or declining a received invite.
type InviteActionResult struct {
	// SpaceID ID of the space the invite was for.
	SpaceID string `json:"space_id"`

	// SpaceName Name of the space the invite was for.
	SpaceName string `json:"space_name"`
}

// InviteStatus Status of a sent invite. `pending` means it's still awaiting a
// response; `declined` means the invitee declined it. A declined invite
// still occupies the email's slot for the space (one pending-or-declined
// invite per email), so it must be cancelled before that email can be
// re-invited.
type InviteStatus string

// Invoice Invoice summary.
type Invoice struct {
	// ID Opaque invoice ID used to look up invoice details.
	ID string `json:"id"`

	// InvoiceDate Date the invoice was issued.
	InvoiceDate time.Time `json:"invoice_date"`

	// InvoiceNumber Human-readable invoice number (e.g. "INV-12345").
	InvoiceNumber string `json:"invoice_number"`

	// Status Invoice status:
	// - `paid` — invoice has been paid.
	// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
	// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
	Status InvoiceStatus `json:"status"`

	// Total Invoice total.
	Total float64 `json:"total"`
}

// InvoiceDetail Line-item breakdown of an invoice.
type InvoiceDetail struct {
	// LineItems Line items that make up the invoice.
	LineItems []InvoiceLineItem `json:"line_items"`
}

// InvoiceLineItem A single line item on an invoice.
type InvoiceLineItem struct {
	// DatabaseID Ghost database ID this line item is attributed to, if any.
	DatabaseID *string `json:"database_id,omitempty"`

	// DetailedSpec Additional spec details (e.g. tier, size).
	DetailedSpec *string `json:"detailed_spec,omitempty"`

	// LineTotal Total charge for this line (`quantity` × `unit_price`).
	LineTotal float64 `json:"line_total"`

	// ProductType Product category (e.g. storage, compute).
	ProductType string `json:"product_type"`

	// Quantity Quantity billed. Units depend on `product_type`.
	Quantity float64 `json:"quantity"`

	// UnitPrice Price per unit of `quantity`.
	UnitPrice float64 `json:"unit_price"`
}

// InvoiceStatus Invoice status:
// - `paid` — invoice has been paid.
// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
type InvoiceStatus string

// InvoicesResponse A list of invoices for a space.
type InvoicesResponse struct {
	// Invoices Recent invoices, most recent first.
	Invoices []Invoice `json:"invoices"`
}

// LeaveSpaceResult Result of leaving a space.
type LeaveSpaceResult struct {
	// SpaceID ID of the space the user left.
	SpaceID string `json:"space_id"`

	// SpaceName Name of the space the user left.
	SpaceName string `json:"space_name"`
}

// LogEntry A single database log entry.
type LogEntry struct {
	// Message Log message text
	Message string `json:"message"`

	// Severity PostgreSQL severity level (e.g. LOG, WARNING, ERROR, FATAL)
	Severity string `json:"severity"`

	// Timestamp Timestamp of the log entry (RFC3339 format, with nanosecond precision)
	Timestamp time.Time `json:"timestamp"`
}

// LogoutRequest Request to log out by revoking a refresh token.
type LogoutRequest struct {
	// RefreshToken Refresh token to revoke.
	RefreshToken string `json:"refreshToken"`
}

// LogsResponse A page of database log entries.
type LogsResponse struct {
	// Entries Log entries, most recent first.
	Entries []LogEntry `json:"entries"`

	// LastCursor Opaque cursor for the next page of results. Present when more log
	// entries exist older than the last entry in this response. Pass
	// this value as the `cursor` query parameter to retrieve the next
	// page. Absent when there are no further results.
	LastCursor *string `json:"last_cursor,omitempty"`
}

// Member A member of a Ghost space.
type Member struct {
	// Email Email address of the member.
	Email string `json:"email"`

	// Name Display name of the member.
	Name string `json:"name"`

	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role MemberRole `json:"role"`

	// UserID User ID of the member.
	UserID int64 `json:"user_id"`
}

// MemberRole A member's role within a space. The `owner` role belongs to the user
// who created the space; every space has exactly one owner, so `owner`
// is never accepted as an input when granting a role. On the `Space`
// schema, this is the caller's own role in the space, omitted for
// API-key authentication (API keys are space-scoped and carry no
// member identity).
type MemberRole string

// PaymentMethod A payment method on file for a space.
type PaymentMethod struct {
	// Brand Card brand (e.g. `visa`, `mastercard`).
	Brand string `json:"brand"`

	// ExpMonth Card expiration month (1-12).
	ExpMonth int `json:"exp_month"`

	// ExpYear Card expiration year (four digits).
	ExpYear int `json:"exp_year"`

	// ID Payment method ID.
	ID string `json:"id"`

	// Last4 Last four digits of the card number.
	Last4 string `json:"last4"`

	// PendingDeletion True if deletion has been scheduled for this payment method. The deletion can be cancelled until processed.
	PendingDeletion bool `json:"pending_deletion"`

	// Primary True if this is the primary payment method for the space.
	Primary bool `json:"primary"`
}

// PaymentMethodsResponse A list of payment methods on file for a space.
type PaymentMethodsResponse struct {
	// PaymentMethods Payment methods on file for the space.
	PaymentMethods []PaymentMethod `json:"payment_methods"`
}

// PaymentSetupResponse Stripe Setup Intent details for collecting a new payment method.
type PaymentSetupResponse struct {
	// ClientSecret Stripe Setup Intent client secret.
	ClientSecret string `json:"client_secret"`

	// PaymentURL URL of the hosted payment page for collecting card details.
	PaymentURL string `json:"payment_url"`
}

// Pricing Pricing data grouped by category.
type Pricing struct {
	// Dedicated Pricing for dedicated databases.
	Dedicated DedicatedPricing `json:"dedicated"`

	// Standard Pricing for standard (non-dedicated) databases, which share a
	// space-wide compute allowance.
	Standard StandardPricing `json:"standard"`
}

// ReceivedInvite A pending invite the authenticated user has received.
type ReceivedInvite struct {
	// CreatedAt When the invite was created.
	CreatedAt time.Time `json:"created_at"`

	// InviterEmail Email address of the user who sent the invite.
	InviterEmail string `json:"inviter_email"`

	// InviterName Display name of the user who sent the invite.
	InviterName string `json:"inviter_name"`

	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role MemberRole `json:"role"`

	// SpaceID ID of the space the user is invited to.
	SpaceID string `json:"space_id"`

	// SpaceName Name of the space the user is invited to.
	SpaceName string `json:"space_name"`
}

// RenameDatabaseRequest Request to rename a database.
type RenameDatabaseRequest struct {
	// Name New name for the database.
	Name string `json:"name"`
}

// RenameSpaceRequest Request to rename a space.
type RenameSpaceRequest struct {
	// Name New name for the space.
	Name string `json:"name"`
}

// RenameSpaceResult Result of renaming a space.
type RenameSpaceResult struct {
	// ID Space ID.
	ID string `json:"id"`

	// NewName Space name after the rename.
	NewName string `json:"new_name"`

	// OldName Space name before the rename.
	OldName string `json:"old_name"`
}

// ShareDatabaseRequest Options for creating a database share.
type ShareDatabaseRequest struct {
	// ExpiresAt Time after which the share expires. If omitted, the share does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// Space A Ghost space.
type Space struct {
	// ID Space ID.
	ID string `json:"id"`

	// Name Space name.
	Name string `json:"name"`

	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role *MemberRole `json:"role,omitempty"`
}

// SpaceDetail Detailed information about a single Ghost space.
type SpaceDetail struct {
	// ID Space ID.
	ID string `json:"id"`

	// Name Space name.
	Name string `json:"name"`

	// Owner The space owner. Populated for user authentication; omitted for API key authentication.
	Owner *Member `json:"owner,omitempty"`

	// Role The caller's role in the space. Populated for user authentication; omitted for API key authentication.
	Role *MemberRole `json:"role,omitempty"`
}

// SpaceUsage Space-level usage and cost for the current billing cycle.
type SpaceUsage struct {
	// BillingPeriodEnd End of the current billing cycle.
	BillingPeriodEnd *time.Time `json:"billing_period_end,omitempty"`

	// BillingPeriodStart Start of the current billing cycle.
	BillingPeriodStart *time.Time `json:"billing_period_start,omitempty"`

	// ComputeLimitMinutes Compute-minute quota for the space. When exceeded, all standard
	// databases in the space are automatically paused. `null` means no
	// limit — only possible when `overages_enabled` is true.
	ComputeLimitMinutes *int64 `json:"compute_limit_minutes,omitempty"`

	// ComputeMinutes Total compute minutes used across all databases in the space during the current billing cycle.
	ComputeMinutes int64 `json:"compute_minutes"`

	// CostToDate Gross cost accrued so far this billing cycle.
	CostToDate *float64 `json:"cost_to_date,omitempty"`

	// EstimatedTotalCost Projected gross total for the current billing cycle based on usage to date.
	EstimatedTotalCost *float64 `json:"estimated_total_cost,omitempty"`

	// FreeComputeMinutes Compute minutes included per billing cycle at no additional charge,
	// shared across all standard databases in the space. Usage beyond this
	// is billed only when `overages_enabled` is true.
	FreeComputeMinutes int64 `json:"free_compute_minutes"`

	// OveragesEnabled Whether the space has compute overages enabled.
	OveragesEnabled bool `json:"overages_enabled"`

	// StorageLimitMib Storage quota for the space, in MiB.
	StorageLimitMib int64 `json:"storage_limit_mib"`

	// StorageMib Total storage used across all databases in the space, in MiB.
	StorageMib int64 `json:"storage_mib"`
}

// StandardComputePrice Pricing for standard (shared) compute used beyond the free monthly
// allowance.
type StandardComputePrice struct {
	// IncludedComputeHoursPerMonth Compute-hours included per month at no additional charge, shared
	// across all standard databases in the space. Only usage above this
	// amount is billed at `price_per_hour`.
	IncludedComputeHoursPerMonth int `json:"included_compute_hours_per_month"`

	// PricePerHour Price per compute-hour used beyond the included monthly allowance,
	// metered in 15-minute increments.
	PricePerHour float64 `json:"price_per_hour"`
}

// StandardPricing Pricing for standard (non-dedicated) databases, which share a
// space-wide compute allowance.
type StandardPricing struct {
	// Compute Pricing for standard (shared) compute used beyond the free monthly
	// allowance.
	Compute StandardComputePrice `json:"compute"`
}

// StatusResponse Generic success response.
type StatusResponse struct {
	// Status Status string (e.g. `success`).
	Status string `json:"status"`
}

// StoragePrice Storage pricing.
type StoragePrice struct {
	// IncludedGibPerDatabase GiB of storage included per database at no additional charge. Only
	// storage above this amount is billed at `price_per_gib_hour`.
	IncludedGibPerDatabase int `json:"included_gib_per_database"`

	// PricePerGibHour Price per GiB per hour of provisioned storage above the included amount.
	PricePerGibHour float64 `json:"price_per_gib_hour"`

	// PricePerGibMonth Price per GiB per month of provisioned storage above the included amount.
	PricePerGibMonth float64 `json:"price_per_gib_month"`
}

// TrackRequest An analytics event to record.
type TrackRequest struct {
	// Event Event name.
	Event string `json:"event"`

	// Properties Free-form event properties.
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// UpdateMemberRoleRequest Request to change a member's role within a space.
type UpdateMemberRoleRequest struct {
	// Role A member's role within a space. The `owner` role belongs to the user
	// who created the space; every space has exactly one owner, so `owner`
	// is never accepted as an input when granting a role. On the `Space`
	// schema, this is the caller's own role in the space, omitted for
	// API-key authentication (API keys are space-scoped and carry no
	// member identity).
	Role MemberRole `json:"role"`
}

// UpdateOverageSettingsRequest Request body for updating compute overage settings on a space.
type UpdateOverageSettingsRequest struct {
	// ComputeLimitMinutes Optional when `enabled` is true: the monthly compute-minute limit
	// above which standard databases auto-pause. Must be greater than
	// the free-tier limit (6000 minutes). Omit or set to `null` for no
	// limit — the user is billed for all overage usage with no upper
	// bound. Must be omitted (or `null`) when `enabled` is false; on
	// disable the server resets the limit to the free-tier default.
	ComputeLimitMinutes *int64 `json:"compute_limit_minutes,omitempty"`

	// Enabled Set to true to enable overages, false to disable.
	Enabled bool `json:"enabled"`
}

// UpdatePasswordRequest Request to reset the database password.
type UpdatePasswordRequest struct {
	// Password New PostgreSQL password for the default user.
	Password string `json:"password"`
}

// UserInfo Authenticated user details.
type UserInfo struct {
	// Email User email address.
	Email string `json:"email"`

	// ID User ID.
	ID string `json:"id"`

	// Name User's full name.
	Name string `json:"name"`
}

// APIKeyPrefix defines model for ApiKeyPrefix.
type APIKeyPrefix = string

// DatabaseRef defines model for DatabaseRef.
type DatabaseRef = string

// InviteEmail defines model for InviteEmail.
type InviteEmail = string

// InvoiceID defines model for InvoiceId.
type InvoiceID = string

// MemberUserID defines model for MemberUserId.
type MemberUserID = int64

// PaymentID defines model for PaymentId.
type PaymentID = string

// ShareToken defines model for ShareToken.
type ShareToken = string

// SpaceID defines model for SpaceId.
type SpaceID = string

// DatabaseLogsParams defines parameters for DatabaseLogs.
type DatabaseLogsParams struct {
	// Cursor Opaque pagination cursor returned as `last_cursor` in a previous
	// response. When provided, returns the next page of logs older than
	// the cursor position.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Until Upper bound timestamp — return logs at or before this time (RFC3339 format, e.g., 2024-01-15T10:00:00Z). Defaults to now.
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`

	// Since Lower bound timestamp — fetch logs after this time (RFC3339 format, e.g., 2024-01-15T09:00:00Z)
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Search Full-text search terms to filter log lines. Repeat the parameter
	// for multiple values (e.g. `?search=slow+query&search=ERROR`).
	Search *[]string `form:"search,omitempty" json:"search,omitempty"`

	// Severity Severity levels to filter results. Repeat the parameter for multiple
	// values (e.g. `?severity=ERROR&severity=WARNING`). Common values
	// include `LOG`, `WARNING`, `ERROR`, and `FATAL`; PostgreSQL may also
	// emit `DEBUG*`, `INFO`, `NOTICE`, and `PANIC`.
	Severity *[]string `form:"severity,omitempty" json:"severity,omitempty"`
}

// AnalyticsIdentifyJSONRequestBody defines body for AnalyticsIdentify for application/json ContentType.
type AnalyticsIdentifyJSONRequestBody = IdentifyRequest

// AnalyticsTrackJSONRequestBody defines body for AnalyticsTrack for application/json ContentType.
type AnalyticsTrackJSONRequestBody = TrackRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = FeedbackRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// ForkDatabaseJSONRequestBody defines body for ForkDatabase for application/json ContentType.
type ForkDatabaseJSONRequestBody = ForkDatabaseRequest

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UpdatePasswordRequest

// RenameDatabaseJSONRequestBody defines body for RenameDatabase for application/json ContentType.
type RenameDatabaseJSONRequestBody = RenameDatabaseRequest

// ShareDatabaseJSONRequestBody defines body for ShareDatabase for application/json ContentType.
type ShareDatabaseJSONRequestBody = ShareDatabaseRequest

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRoleRequest

// UpdateOveragesJSONRequestBody defines body for UpdateOverages for application/json ContentType.
type UpdateOveragesJSONRequestBody = UpdateOverageSettingsRequest

// RenameSpaceJSONRequestBody defines body for RenameSpace for application/json ContentType.
type RenameSpaceJSONRequestBody = RenameSpaceRequest
