// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock/mock_client.go -package=mock ClientWithResponsesInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	api "github.com/timescale/ghost/internal/api"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// AnalyticsIdentify mocks base method.
func (m *MockClientInterface) AnalyticsIdentify(ctx context.Context, body api.AnalyticsIdentifyJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsIdentify", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsIdentify indicates an expected call of AnalyticsIdentify.
func (mr *MockClientInterfaceMockRecorder) AnalyticsIdentify(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsIdentify", reflect.TypeOf((*MockClientInterface)(nil).AnalyticsIdentify), varargs...)
}

// AnalyticsIdentifyWithBody mocks base method.
func (m *MockClientInterface) AnalyticsIdentifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsIdentifyWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsIdentifyWithBody indicates an expected call of AnalyticsIdentifyWithBody.
func (mr *MockClientInterfaceMockRecorder) AnalyticsIdentifyWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsIdentifyWithBody", reflect.TypeOf((*MockClientInterface)(nil).AnalyticsIdentifyWithBody), varargs...)
}

// AnalyticsTrack mocks base method.
func (m *MockClientInterface) AnalyticsTrack(ctx context.Context, body api.AnalyticsTrackJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsTrack", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsTrack indicates an expected call of AnalyticsTrack.
func (mr *MockClientInterfaceMockRecorder) AnalyticsTrack(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsTrack", reflect.TypeOf((*MockClientInterface)(nil).AnalyticsTrack), varargs...)
}

// AnalyticsTrackWithBody mocks base method.
func (m *MockClientInterface) AnalyticsTrackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsTrackWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsTrackWithBody indicates an expected call of AnalyticsTrackWithBody.
func (mr *MockClientInterfaceMockRecorder) AnalyticsTrackWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsTrackWithBody", reflect.TypeOf((*MockClientInterface)(nil).AnalyticsTrackWithBody), varargs...)
}

// AuthInfo mocks base method.
func (m *MockClientInterface) AuthInfo(ctx context.Context, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthInfo", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthInfo indicates an expected call of AuthInfo.
func (mr *MockClientInterfaceMockRecorder) AuthInfo(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthInfo", reflect.TypeOf((*MockClientInterface)(nil).AuthInfo), varargs...)
}

// CancelPaymentMethodDeletion mocks base method.
func (m *MockClientInterface) CancelPaymentMethodDeletion(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelPaymentMethodDeletion", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPaymentMethodDeletion indicates an expected call of CancelPaymentMethodDeletion.
func (mr *MockClientInterfaceMockRecorder) CancelPaymentMethodDeletion(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPaymentMethodDeletion", reflect.TypeOf((*MockClientInterface)(nil).CancelPaymentMethodDeletion), varargs...)
}

// CreateApiKey mocks base method.
func (m *MockClientInterface) CreateApiKey(ctx context.Context, spaceId api.SpaceId, body api.CreateApiKeyJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateApiKey", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockClientInterfaceMockRecorder) CreateApiKey(ctx, spaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockClientInterface)(nil).CreateApiKey), varargs...)
}

// CreateApiKeyWithBody mocks base method.
func (m *MockClientInterface) CreateApiKeyWithBody(ctx context.Context, spaceId api.SpaceId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateApiKeyWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKeyWithBody indicates an expected call of CreateApiKeyWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateApiKeyWithBody(ctx, spaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKeyWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateApiKeyWithBody), varargs...)
}

// CreateDatabase mocks base method.
func (m *MockClientInterface) CreateDatabase(ctx context.Context, spaceId api.SpaceId, body api.CreateDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabase indicates an expected call of CreateDatabase.
func (mr *MockClientInterfaceMockRecorder) CreateDatabase(ctx, spaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabase", reflect.TypeOf((*MockClientInterface)(nil).CreateDatabase), varargs...)
}

// CreateDatabaseWithBody mocks base method.
func (m *MockClientInterface) CreateDatabaseWithBody(ctx context.Context, spaceId api.SpaceId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabaseWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseWithBody indicates an expected call of CreateDatabaseWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateDatabaseWithBody(ctx, spaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateDatabaseWithBody), varargs...)
}

// CreatePaymentMethodSetup mocks base method.
func (m *MockClientInterface) CreatePaymentMethodSetup(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePaymentMethodSetup", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentMethodSetup indicates an expected call of CreatePaymentMethodSetup.
func (mr *MockClientInterfaceMockRecorder) CreatePaymentMethodSetup(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentMethodSetup", reflect.TypeOf((*MockClientInterface)(nil).CreatePaymentMethodSetup), varargs...)
}

// CreateSpace mocks base method.
func (m *MockClientInterface) CreateSpace(ctx context.Context, body api.CreateSpaceJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSpace", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSpace indicates an expected call of CreateSpace.
func (mr *MockClientInterfaceMockRecorder) CreateSpace(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpace", reflect.TypeOf((*MockClientInterface)(nil).CreateSpace), varargs...)
}

// CreateSpaceWithBody mocks base method.
func (m *MockClientInterface) CreateSpaceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSpaceWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSpaceWithBody indicates an expected call of CreateSpaceWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateSpaceWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpaceWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateSpaceWithBody), varargs...)
}

// DatabaseLogs mocks base method.
func (m *MockClientInterface) DatabaseLogs(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, params *api.DatabaseLogsParams, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DatabaseLogs", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseLogs indicates an expected call of DatabaseLogs.
func (mr *MockClientInterfaceMockRecorder) DatabaseLogs(ctx, spaceId, databaseRef, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseLogs", reflect.TypeOf((*MockClientInterface)(nil).DatabaseLogs), varargs...)
}

// DeleteApiKey mocks base method.
func (m *MockClientInterface) DeleteApiKey(ctx context.Context, spaceId api.SpaceId, prefix api.ApiKeyPrefix, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, prefix}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiKey", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiKey indicates an expected call of DeleteApiKey.
func (mr *MockClientInterfaceMockRecorder) DeleteApiKey(ctx, spaceId, prefix any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, prefix}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiKey", reflect.TypeOf((*MockClientInterface)(nil).DeleteApiKey), varargs...)
}

// DeleteDatabase mocks base method.
func (m *MockClientInterface) DeleteDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDatabase indicates an expected call of DeleteDatabase.
func (mr *MockClientInterfaceMockRecorder) DeleteDatabase(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabase", reflect.TypeOf((*MockClientInterface)(nil).DeleteDatabase), varargs...)
}

// DeletePaymentMethod mocks base method.
func (m *MockClientInterface) DeletePaymentMethod(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePaymentMethod", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePaymentMethod indicates an expected call of DeletePaymentMethod.
func (mr *MockClientInterfaceMockRecorder) DeletePaymentMethod(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethod", reflect.TypeOf((*MockClientInterface)(nil).DeletePaymentMethod), varargs...)
}

// ForkDatabase mocks base method.
func (m *MockClientInterface) ForkDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.ForkDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForkDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkDatabase indicates an expected call of ForkDatabase.
func (mr *MockClientInterfaceMockRecorder) ForkDatabase(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkDatabase", reflect.TypeOf((*MockClientInterface)(nil).ForkDatabase), varargs...)
}

// ForkDatabaseWithBody mocks base method.
func (m *MockClientInterface) ForkDatabaseWithBody(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForkDatabaseWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkDatabaseWithBody indicates an expected call of ForkDatabaseWithBody.
func (mr *MockClientInterfaceMockRecorder) ForkDatabaseWithBody(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkDatabaseWithBody", reflect.TypeOf((*MockClientInterface)(nil).ForkDatabaseWithBody), varargs...)
}

// GetDatabase mocks base method.
func (m *MockClientInterface) GetDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockClientInterfaceMockRecorder) GetDatabase(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockClientInterface)(nil).GetDatabase), varargs...)
}

// GetInvoice mocks base method.
func (m *MockClientInterface) GetInvoice(ctx context.Context, spaceId api.SpaceId, invoiceId string, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, invoiceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvoice", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoice indicates an expected call of GetInvoice.
func (mr *MockClientInterfaceMockRecorder) GetInvoice(ctx, spaceId, invoiceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, invoiceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoice", reflect.TypeOf((*MockClientInterface)(nil).GetInvoice), varargs...)
}

// GetPaymentMethod mocks base method.
func (m *MockClientInterface) GetPaymentMethod(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPaymentMethod", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentMethod indicates an expected call of GetPaymentMethod.
func (mr *MockClientInterfaceMockRecorder) GetPaymentMethod(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentMethod", reflect.TypeOf((*MockClientInterface)(nil).GetPaymentMethod), varargs...)
}

// GetPricing mocks base method.
func (m *MockClientInterface) GetPricing(ctx context.Context, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPricing", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricing indicates an expected call of GetPricing.
func (mr *MockClientInterfaceMockRecorder) GetPricing(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricing", reflect.TypeOf((*MockClientInterface)(nil).GetPricing), varargs...)
}

// Health mocks base method.
func (m *MockClientInterface) Health(ctx context.Context, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Health", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockClientInterfaceMockRecorder) Health(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockClientInterface)(nil).Health), varargs...)
}

// ListApiKeys mocks base method.
func (m *MockClientInterface) ListApiKeys(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListApiKeys", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiKeys indicates an expected call of ListApiKeys.
func (mr *MockClientInterfaceMockRecorder) ListApiKeys(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiKeys", reflect.TypeOf((*MockClientInterface)(nil).ListApiKeys), varargs...)
}

// ListDatabases mocks base method.
func (m *MockClientInterface) ListDatabases(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDatabases", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabases indicates an expected call of ListDatabases.
func (mr *MockClientInterfaceMockRecorder) ListDatabases(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabases", reflect.TypeOf((*MockClientInterface)(nil).ListDatabases), varargs...)
}

// ListInvoices mocks base method.
func (m *MockClientInterface) ListInvoices(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInvoices", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoices indicates an expected call of ListInvoices.
func (mr *MockClientInterfaceMockRecorder) ListInvoices(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoices", reflect.TypeOf((*MockClientInterface)(nil).ListInvoices), varargs...)
}

// ListPaymentMethods mocks base method.
func (m *MockClientInterface) ListPaymentMethods(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPaymentMethods", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentMethods indicates an expected call of ListPaymentMethods.
func (mr *MockClientInterfaceMockRecorder) ListPaymentMethods(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethods", reflect.TypeOf((*MockClientInterface)(nil).ListPaymentMethods), varargs...)
}

// ListShares mocks base method.
func (m *MockClientInterface) ListShares(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListShares", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShares indicates an expected call of ListShares.
func (mr *MockClientInterfaceMockRecorder) ListShares(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShares", reflect.TypeOf((*MockClientInterface)(nil).ListShares), varargs...)
}

// ListSpaces mocks base method.
func (m *MockClientInterface) ListSpaces(ctx context.Context, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSpaces", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpaces indicates an expected call of ListSpaces.
func (mr *MockClientInterfaceMockRecorder) ListSpaces(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpaces", reflect.TypeOf((*MockClientInterface)(nil).ListSpaces), varargs...)
}

// Logout mocks base method.
func (m *MockClientInterface) Logout(ctx context.Context, body api.LogoutJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logout", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockClientInterfaceMockRecorder) Logout(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockClientInterface)(nil).Logout), varargs...)
}

// LogoutWithBody mocks base method.
func (m *MockClientInterface) LogoutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogoutWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutWithBody indicates an expected call of LogoutWithBody.
func (mr *MockClientInterfaceMockRecorder) LogoutWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutWithBody", reflect.TypeOf((*MockClientInterface)(nil).LogoutWithBody), varargs...)
}

// PauseDatabase mocks base method.
func (m *MockClientInterface) PauseDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PauseDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseDatabase indicates an expected call of PauseDatabase.
func (mr *MockClientInterfaceMockRecorder) PauseDatabase(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseDatabase", reflect.TypeOf((*MockClientInterface)(nil).PauseDatabase), varargs...)
}

// RenameDatabase mocks base method.
func (m *MockClientInterface) RenameDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.RenameDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameDatabase indicates an expected call of RenameDatabase.
func (mr *MockClientInterfaceMockRecorder) RenameDatabase(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDatabase", reflect.TypeOf((*MockClientInterface)(nil).RenameDatabase), varargs...)
}

// RenameDatabaseWithBody mocks base method.
func (m *MockClientInterface) RenameDatabaseWithBody(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameDatabaseWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameDatabaseWithBody indicates an expected call of RenameDatabaseWithBody.
func (mr *MockClientInterfaceMockRecorder) RenameDatabaseWithBody(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDatabaseWithBody", reflect.TypeOf((*MockClientInterface)(nil).RenameDatabaseWithBody), varargs...)
}

// ResumeDatabase mocks base method.
func (m *MockClientInterface) ResumeDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeDatabase indicates an expected call of ResumeDatabase.
func (mr *MockClientInterfaceMockRecorder) ResumeDatabase(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeDatabase", reflect.TypeOf((*MockClientInterface)(nil).ResumeDatabase), varargs...)
}

// RevokeShare mocks base method.
func (m *MockClientInterface) RevokeShare(ctx context.Context, spaceId api.SpaceId, shareToken string, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, shareToken}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeShare", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeShare indicates an expected call of RevokeShare.
func (mr *MockClientInterfaceMockRecorder) RevokeShare(ctx, spaceId, shareToken any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, shareToken}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeShare", reflect.TypeOf((*MockClientInterface)(nil).RevokeShare), varargs...)
}

// SetPaymentMethodPrimary mocks base method.
func (m *MockClientInterface) SetPaymentMethodPrimary(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPaymentMethodPrimary", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPaymentMethodPrimary indicates an expected call of SetPaymentMethodPrimary.
func (mr *MockClientInterfaceMockRecorder) SetPaymentMethodPrimary(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaymentMethodPrimary", reflect.TypeOf((*MockClientInterface)(nil).SetPaymentMethodPrimary), varargs...)
}

// ShareDatabase mocks base method.
func (m *MockClientInterface) ShareDatabase(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.ShareDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShareDatabase", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareDatabase indicates an expected call of ShareDatabase.
func (mr *MockClientInterfaceMockRecorder) ShareDatabase(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareDatabase", reflect.TypeOf((*MockClientInterface)(nil).ShareDatabase), varargs...)
}

// ShareDatabaseWithBody mocks base method.
func (m *MockClientInterface) ShareDatabaseWithBody(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShareDatabaseWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareDatabaseWithBody indicates an expected call of ShareDatabaseWithBody.
func (mr *MockClientInterfaceMockRecorder) ShareDatabaseWithBody(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareDatabaseWithBody", reflect.TypeOf((*MockClientInterface)(nil).ShareDatabaseWithBody), varargs...)
}

// SpaceStatus mocks base method.
func (m *MockClientInterface) SpaceStatus(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SpaceStatus", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceStatus indicates an expected call of SpaceStatus.
func (mr *MockClientInterfaceMockRecorder) SpaceStatus(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceStatus", reflect.TypeOf((*MockClientInterface)(nil).SpaceStatus), varargs...)
}

// SpaceUsage mocks base method.
func (m *MockClientInterface) SpaceUsage(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SpaceUsage", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceUsage indicates an expected call of SpaceUsage.
func (mr *MockClientInterfaceMockRecorder) SpaceUsage(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceUsage", reflect.TypeOf((*MockClientInterface)(nil).SpaceUsage), varargs...)
}

// SubmitFeedback mocks base method.
func (m *MockClientInterface) SubmitFeedback(ctx context.Context, body api.SubmitFeedbackJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitFeedback", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitFeedback indicates an expected call of SubmitFeedback.
func (mr *MockClientInterfaceMockRecorder) SubmitFeedback(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFeedback", reflect.TypeOf((*MockClientInterface)(nil).SubmitFeedback), varargs...)
}

// SubmitFeedbackWithBody mocks base method.
func (m *MockClientInterface) SubmitFeedbackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitFeedbackWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitFeedbackWithBody indicates an expected call of SubmitFeedbackWithBody.
func (mr *MockClientInterfaceMockRecorder) SubmitFeedbackWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFeedbackWithBody", reflect.TypeOf((*MockClientInterface)(nil).SubmitFeedbackWithBody), varargs...)
}

// UpdatePassword mocks base method.
func (m *MockClientInterface) UpdatePassword(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.UpdatePasswordJSONRequestBody, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePassword", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockClientInterfaceMockRecorder) UpdatePassword(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockClientInterface)(nil).UpdatePassword), varargs...)
}

// UpdatePasswordWithBody mocks base method.
func (m *MockClientInterface) UpdatePasswordWithBody(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePasswordWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordWithBody indicates an expected call of UpdatePasswordWithBody.
func (mr *MockClientInterfaceMockRecorder) UpdatePasswordWithBody(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordWithBody", reflect.TypeOf((*MockClientInterface)(nil).UpdatePasswordWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// AnalyticsIdentifyWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) AnalyticsIdentifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.AnalyticsIdentifyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsIdentifyWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AnalyticsIdentifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsIdentifyWithBodyWithResponse indicates an expected call of AnalyticsIdentifyWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) AnalyticsIdentifyWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsIdentifyWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).AnalyticsIdentifyWithBodyWithResponse), varargs...)
}

// AnalyticsIdentifyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) AnalyticsIdentifyWithResponse(ctx context.Context, body api.AnalyticsIdentifyJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.AnalyticsIdentifyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsIdentifyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AnalyticsIdentifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsIdentifyWithResponse indicates an expected call of AnalyticsIdentifyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) AnalyticsIdentifyWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsIdentifyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).AnalyticsIdentifyWithResponse), varargs...)
}

// AnalyticsTrackWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) AnalyticsTrackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.AnalyticsTrackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsTrackWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AnalyticsTrackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsTrackWithBodyWithResponse indicates an expected call of AnalyticsTrackWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) AnalyticsTrackWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsTrackWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).AnalyticsTrackWithBodyWithResponse), varargs...)
}

// AnalyticsTrackWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) AnalyticsTrackWithResponse(ctx context.Context, body api.AnalyticsTrackJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.AnalyticsTrackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AnalyticsTrackWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AnalyticsTrackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsTrackWithResponse indicates an expected call of AnalyticsTrackWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) AnalyticsTrackWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsTrackWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).AnalyticsTrackWithResponse), varargs...)
}

// AuthInfoWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) AuthInfoWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.AuthInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthInfoWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AuthInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthInfoWithResponse indicates an expected call of AuthInfoWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) AuthInfoWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthInfoWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).AuthInfoWithResponse), varargs...)
}

// CancelPaymentMethodDeletionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CancelPaymentMethodDeletionWithResponse(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*api.CancelPaymentMethodDeletionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelPaymentMethodDeletionWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CancelPaymentMethodDeletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPaymentMethodDeletionWithResponse indicates an expected call of CancelPaymentMethodDeletionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CancelPaymentMethodDeletionWithResponse(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPaymentMethodDeletionWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CancelPaymentMethodDeletionWithResponse), varargs...)
}

// CreateApiKeyWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateApiKeyWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CreateApiKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateApiKeyWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateApiKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKeyWithBodyWithResponse indicates an expected call of CreateApiKeyWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateApiKeyWithBodyWithResponse(ctx, spaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKeyWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateApiKeyWithBodyWithResponse), varargs...)
}

// CreateApiKeyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateApiKeyWithResponse(ctx context.Context, spaceId api.SpaceId, body api.CreateApiKeyJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CreateApiKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateApiKeyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateApiKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKeyWithResponse indicates an expected call of CreateApiKeyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateApiKeyWithResponse(ctx, spaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKeyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateApiKeyWithResponse), varargs...)
}

// CreateDatabaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateDatabaseWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CreateDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseWithBodyWithResponse indicates an expected call of CreateDatabaseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateDatabaseWithBodyWithResponse(ctx, spaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateDatabaseWithBodyWithResponse), varargs...)
}

// CreateDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, body api.CreateDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CreateDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseWithResponse indicates an expected call of CreateDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateDatabaseWithResponse(ctx, spaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateDatabaseWithResponse), varargs...)
}

// CreatePaymentMethodSetupWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePaymentMethodSetupWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.CreatePaymentMethodSetupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePaymentMethodSetupWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreatePaymentMethodSetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentMethodSetupWithResponse indicates an expected call of CreatePaymentMethodSetupWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePaymentMethodSetupWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentMethodSetupWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreatePaymentMethodSetupWithResponse), varargs...)
}

// CreateSpaceWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateSpaceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CreateSpaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSpaceWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSpaceWithBodyWithResponse indicates an expected call of CreateSpaceWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateSpaceWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpaceWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateSpaceWithBodyWithResponse), varargs...)
}

// CreateSpaceWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateSpaceWithResponse(ctx context.Context, body api.CreateSpaceJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CreateSpaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSpaceWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSpaceWithResponse indicates an expected call of CreateSpaceWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateSpaceWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpaceWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateSpaceWithResponse), varargs...)
}

// DatabaseLogsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DatabaseLogsWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, params *api.DatabaseLogsParams, reqEditors ...api.RequestEditorFn) (*api.DatabaseLogsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DatabaseLogsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DatabaseLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseLogsWithResponse indicates an expected call of DatabaseLogsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DatabaseLogsWithResponse(ctx, spaceId, databaseRef, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseLogsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DatabaseLogsWithResponse), varargs...)
}

// DeleteApiKeyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteApiKeyWithResponse(ctx context.Context, spaceId api.SpaceId, prefix api.ApiKeyPrefix, reqEditors ...api.RequestEditorFn) (*api.DeleteApiKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, prefix}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteApiKeyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteApiKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteApiKeyWithResponse indicates an expected call of DeleteApiKeyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteApiKeyWithResponse(ctx, spaceId, prefix any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, prefix}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiKeyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteApiKeyWithResponse), varargs...)
}

// DeleteDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*api.DeleteDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDatabaseWithResponse indicates an expected call of DeleteDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteDatabaseWithResponse(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeleteDatabaseWithResponse), varargs...)
}

// DeletePaymentMethodWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeletePaymentMethodWithResponse(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*api.DeletePaymentMethodResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePaymentMethodWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeletePaymentMethodResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePaymentMethodWithResponse indicates an expected call of DeletePaymentMethodWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeletePaymentMethodWithResponse(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethodWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DeletePaymentMethodWithResponse), varargs...)
}

// ForkDatabaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ForkDatabaseWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ForkDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForkDatabaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ForkDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkDatabaseWithBodyWithResponse indicates an expected call of ForkDatabaseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ForkDatabaseWithBodyWithResponse(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkDatabaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ForkDatabaseWithBodyWithResponse), varargs...)
}

// ForkDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ForkDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.ForkDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.ForkDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForkDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ForkDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkDatabaseWithResponse indicates an expected call of ForkDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ForkDatabaseWithResponse(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ForkDatabaseWithResponse), varargs...)
}

// GetDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*api.GetDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseWithResponse indicates an expected call of GetDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetDatabaseWithResponse(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetDatabaseWithResponse), varargs...)
}

// GetInvoiceWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetInvoiceWithResponse(ctx context.Context, spaceId api.SpaceId, invoiceId string, reqEditors ...api.RequestEditorFn) (*api.GetInvoiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, invoiceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvoiceWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceWithResponse indicates an expected call of GetInvoiceWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetInvoiceWithResponse(ctx, spaceId, invoiceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, invoiceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetInvoiceWithResponse), varargs...)
}

// GetPaymentMethodWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetPaymentMethodWithResponse(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*api.GetPaymentMethodResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPaymentMethodWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetPaymentMethodResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentMethodWithResponse indicates an expected call of GetPaymentMethodWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetPaymentMethodWithResponse(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentMethodWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetPaymentMethodWithResponse), varargs...)
}

// GetPricingWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetPricingWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetPricingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPricingWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetPricingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricingWithResponse indicates an expected call of GetPricingWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetPricingWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricingWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetPricingWithResponse), varargs...)
}

// HealthWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) HealthWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.HealthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HealthWithResponse", varargs...)
	ret0, _ := ret[0].(*api.HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthWithResponse indicates an expected call of HealthWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) HealthWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).HealthWithResponse), varargs...)
}

// ListApiKeysWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListApiKeysWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.ListApiKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListApiKeysWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListApiKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiKeysWithResponse indicates an expected call of ListApiKeysWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListApiKeysWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiKeysWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListApiKeysWithResponse), varargs...)
}

// ListDatabasesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListDatabasesWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.ListDatabasesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDatabasesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListDatabasesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabasesWithResponse indicates an expected call of ListDatabasesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListDatabasesWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabasesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListDatabasesWithResponse), varargs...)
}

// ListInvoicesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListInvoicesWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.ListInvoicesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInvoicesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListInvoicesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoicesWithResponse indicates an expected call of ListInvoicesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListInvoicesWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoicesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListInvoicesWithResponse), varargs...)
}

// ListPaymentMethodsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListPaymentMethodsWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.ListPaymentMethodsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPaymentMethodsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListPaymentMethodsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentMethodsWithResponse indicates an expected call of ListPaymentMethodsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListPaymentMethodsWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethodsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListPaymentMethodsWithResponse), varargs...)
}

// ListSharesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListSharesWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.ListSharesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSharesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListSharesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSharesWithResponse indicates an expected call of ListSharesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListSharesWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSharesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListSharesWithResponse), varargs...)
}

// ListSpacesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListSpacesWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.ListSpacesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSpacesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ListSpacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpacesWithResponse indicates an expected call of ListSpacesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListSpacesWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpacesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListSpacesWithResponse), varargs...)
}

// LogoutWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) LogoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.LogoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogoutWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutWithBodyWithResponse indicates an expected call of LogoutWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) LogoutWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).LogoutWithBodyWithResponse), varargs...)
}

// LogoutWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) LogoutWithResponse(ctx context.Context, body api.LogoutJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.LogoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogoutWithResponse", varargs...)
	ret0, _ := ret[0].(*api.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutWithResponse indicates an expected call of LogoutWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) LogoutWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).LogoutWithResponse), varargs...)
}

// PauseDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PauseDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*api.PauseDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PauseDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.PauseDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseDatabaseWithResponse indicates an expected call of PauseDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PauseDatabaseWithResponse(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PauseDatabaseWithResponse), varargs...)
}

// RenameDatabaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RenameDatabaseWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.RenameDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameDatabaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RenameDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameDatabaseWithBodyWithResponse indicates an expected call of RenameDatabaseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RenameDatabaseWithBodyWithResponse(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDatabaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RenameDatabaseWithBodyWithResponse), varargs...)
}

// RenameDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RenameDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.RenameDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.RenameDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RenameDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameDatabaseWithResponse indicates an expected call of RenameDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RenameDatabaseWithResponse(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RenameDatabaseWithResponse), varargs...)
}

// ResumeDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ResumeDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, reqEditors ...api.RequestEditorFn) (*api.ResumeDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ResumeDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeDatabaseWithResponse indicates an expected call of ResumeDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ResumeDatabaseWithResponse(ctx, spaceId, databaseRef any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ResumeDatabaseWithResponse), varargs...)
}

// RevokeShareWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RevokeShareWithResponse(ctx context.Context, spaceId api.SpaceId, shareToken string, reqEditors ...api.RequestEditorFn) (*api.RevokeShareResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, shareToken}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeShareWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RevokeShareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeShareWithResponse indicates an expected call of RevokeShareWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RevokeShareWithResponse(ctx, spaceId, shareToken any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, shareToken}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeShareWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RevokeShareWithResponse), varargs...)
}

// SetPaymentMethodPrimaryWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SetPaymentMethodPrimaryWithResponse(ctx context.Context, spaceId api.SpaceId, paymentId api.PaymentId, reqEditors ...api.RequestEditorFn) (*api.SetPaymentMethodPrimaryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, paymentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPaymentMethodPrimaryWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetPaymentMethodPrimaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPaymentMethodPrimaryWithResponse indicates an expected call of SetPaymentMethodPrimaryWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SetPaymentMethodPrimaryWithResponse(ctx, spaceId, paymentId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, paymentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaymentMethodPrimaryWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).SetPaymentMethodPrimaryWithResponse), varargs...)
}

// ShareDatabaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ShareDatabaseWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ShareDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShareDatabaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShareDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareDatabaseWithBodyWithResponse indicates an expected call of ShareDatabaseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ShareDatabaseWithBodyWithResponse(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareDatabaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ShareDatabaseWithBodyWithResponse), varargs...)
}

// ShareDatabaseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ShareDatabaseWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.ShareDatabaseJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.ShareDatabaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShareDatabaseWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShareDatabaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareDatabaseWithResponse indicates an expected call of ShareDatabaseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ShareDatabaseWithResponse(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareDatabaseWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ShareDatabaseWithResponse), varargs...)
}

// SpaceStatusWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SpaceStatusWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.SpaceStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SpaceStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SpaceStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceStatusWithResponse indicates an expected call of SpaceStatusWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SpaceStatusWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceStatusWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).SpaceStatusWithResponse), varargs...)
}

// SpaceUsageWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SpaceUsageWithResponse(ctx context.Context, spaceId api.SpaceId, reqEditors ...api.RequestEditorFn) (*api.SpaceUsageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SpaceUsageWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SpaceUsageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceUsageWithResponse indicates an expected call of SpaceUsageWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SpaceUsageWithResponse(ctx, spaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceUsageWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).SpaceUsageWithResponse), varargs...)
}

// SubmitFeedbackWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SubmitFeedbackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SubmitFeedbackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitFeedbackWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitFeedbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitFeedbackWithBodyWithResponse indicates an expected call of SubmitFeedbackWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SubmitFeedbackWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFeedbackWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).SubmitFeedbackWithBodyWithResponse), varargs...)
}

// SubmitFeedbackWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SubmitFeedbackWithResponse(ctx context.Context, body api.SubmitFeedbackJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SubmitFeedbackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitFeedbackWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitFeedbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitFeedbackWithResponse indicates an expected call of SubmitFeedbackWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SubmitFeedbackWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFeedbackWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).SubmitFeedbackWithResponse), varargs...)
}

// UpdatePasswordWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdatePasswordWithBodyWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.UpdatePasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePasswordWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdatePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordWithBodyWithResponse indicates an expected call of UpdatePasswordWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdatePasswordWithBodyWithResponse(ctx, spaceId, databaseRef, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdatePasswordWithBodyWithResponse), varargs...)
}

// UpdatePasswordWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdatePasswordWithResponse(ctx context.Context, spaceId api.SpaceId, databaseRef api.DatabaseRef, body api.UpdatePasswordJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.UpdatePasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spaceId, databaseRef, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePasswordWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdatePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordWithResponse indicates an expected call of UpdatePasswordWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdatePasswordWithResponse(ctx, spaceId, databaseRef, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spaceId, databaseRef, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdatePasswordWithResponse), varargs...)
}
