package common

import (
	"errors"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestFormatSchema(t *testing.T) {
	tests := []struct {
		name               string
		schema             *DatabaseSchema
		includeDefinitions bool
		expected           string
	}{
		// ==================== Database Header Tests ====================
		{
			name: "database header shows name and id",
			schema: &DatabaseSchema{
				ID:   "abc123",
				Name: "mydb",
			},
			expected: "DATABASE: mydb (abc123)\n",
		},

		// ==================== Table Column Type Tests ====================
		{
			name: "table with simple column types",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "name", Type: "text"},
									{Name: "age", Type: "integer"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  name  TEXT
  age   INTEGER
`,
		},
		{
			name: "SERIAL column is identified correctly",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IsSerial: true, NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "users_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  SERIAL PRIMARY KEY
`,
		},
		{
			name: "BIGSERIAL column is identified correctly",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "bigint", IsSerial: true, NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "events_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  id  BIGSERIAL PRIMARY KEY
`,
		},
		{
			name: "SMALLSERIAL column is identified correctly",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "counters",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "smallint", IsSerial: true, NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "counters_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: counters
  id  SMALLSERIAL PRIMARY KEY
`,
		},
		{
			name: "GENERATED ALWAYS AS IDENTITY column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "products",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IdentityType: "a", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "products_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: products
  id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
`,
		},
		{
			name: "GENERATED BY DEFAULT AS IDENTITY column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "categories",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IdentityType: "d", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "categories_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: categories
  id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
`,
		},
		{
			name: "NOT NULL column without primary key",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "email", Type: "text", NotNull: true},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  email  TEXT NOT NULL
`,
		},
		{
			name: "NOT NULL is not shown for primary key column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "users_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  INTEGER PRIMARY KEY
`,
		},
		{
			name: "NOT NULL is not shown for SERIAL column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IsSerial: true, NotNull: true},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  SERIAL
`,
		},
		{
			name: "NOT NULL is not shown for IDENTITY column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IdentityType: "a", NotNull: true},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  INTEGER GENERATED ALWAYS AS IDENTITY
`,
		},
		{
			name: "DEFAULT value is shown",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "status", Type: "text", Default: "'active'"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  status  TEXT DEFAULT 'active'
`,
		},
		{
			name: "DEFAULT is not shown for SERIAL column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IsSerial: true, Default: "nextval('users_id_seq')"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  SERIAL
`,
		},
		{
			name: "DEFAULT is not shown for IDENTITY column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IdentityType: "a", Default: "nextval('users_id_seq')"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  INTEGER GENERATED ALWAYS AS IDENTITY
`,
		},
		{
			name: "column type is uppercased",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "data", Type: "character varying(255)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  data  CHARACTER VARYING(255)
`,
		},

		// ==================== Single-Column Constraint Inlining Tests ====================
		{
			name: "single-column primary key is inlined",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "users_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id  INTEGER PRIMARY KEY
`,
		},
		{
			name: "single-column unique constraint is inlined",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "email", Type: "text"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintUnique, Name: "users_email_key", Columns: []string{"email"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  email  TEXT UNIQUE
`,
		},
		{
			name: "single-column foreign key is inlined",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "posts",
								Columns: []TableColumnSchema{
									{Name: "user_id", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintForeignKey, Name: "posts_user_id_fkey", Columns: []string{"user_id"}, RefTable: "users", RefColumns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: posts
  user_id  INTEGER REFERENCES users(id)
`,
		},
		{
			name: "single-column check constraint is inlined",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "age", Type: "integer"},
								},
								Checks: []CheckConstraint{
									{Name: "users_age_check", Columns: []string{"age"}, Expression: "CHECK ((age >= 0))"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  age  INTEGER CHECK ((age >= 0))
`,
		},

		// ==================== Multi-Column Constraint Tests ====================
		{
			name: "multi-column primary key is on separate line",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "order_items",
								Columns: []TableColumnSchema{
									{Name: "order_id", Type: "integer"},
									{Name: "product_id", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "order_items_pkey", Columns: []string{"order_id", "product_id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: order_items
  order_id    INTEGER
  product_id  INTEGER

  PRIMARY KEY (order_id, product_id)
`,
		},
		{
			name: "multi-column unique constraint is on separate line",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "posts",
								Columns: []TableColumnSchema{
									{Name: "user_id", Type: "integer"},
									{Name: "slug", Type: "text"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintUnique, Name: "posts_user_id_slug_key", Columns: []string{"user_id", "slug"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: posts
  user_id  INTEGER
  slug     TEXT

  UNIQUE (user_id, slug)
`,
		},
		{
			name: "multi-column foreign key is on separate line",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "notes",
								Columns: []TableColumnSchema{
									{Name: "order_id", Type: "integer"},
									{Name: "product_id", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintForeignKey, Name: "notes_fkey", Columns: []string{"order_id", "product_id"}, RefTable: "order_items", RefColumns: []string{"order_id", "product_id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: notes
  order_id    INTEGER
  product_id  INTEGER

  FOREIGN KEY (order_id, product_id) REFERENCES order_items(order_id, product_id)
`,
		},
		{
			name: "multi-column check constraint is on separate line",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "start_time", Type: "timestamp"},
									{Name: "end_time", Type: "timestamp"},
								},
								Checks: []CheckConstraint{
									{Name: "events_time_check", Columns: []string{"start_time", "end_time"}, Expression: "CHECK ((end_time > start_time))"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  start_time  TIMESTAMP
  end_time    TIMESTAMP

  CHECK ((end_time > start_time))
`,
		},

		// ==================== Multiple Constraints on Same Column Tests ====================
		{
			name: "multiple foreign keys on same column are shown separately",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "audit_log",
								Columns: []TableColumnSchema{
									{Name: "user_id", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintForeignKey, Name: "audit_log_user_fk1", Columns: []string{"user_id"}, RefTable: "users", RefColumns: []string{"id"}},
									{Type: ConstraintForeignKey, Name: "audit_log_user_fk2", Columns: []string{"user_id"}, RefTable: "admins", RefColumns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: audit_log
  user_id  INTEGER

  FOREIGN KEY (user_id) REFERENCES users(id)
  FOREIGN KEY (user_id) REFERENCES admins(id)
`,
		},
		{
			name: "multiple check constraints on same column are shown separately",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "scores",
								Columns: []TableColumnSchema{
									{Name: "value", Type: "integer"},
								},
								Checks: []CheckConstraint{
									{Name: "positive_check", Columns: []string{"value"}, Expression: "CHECK ((value >= 0))"},
									{Name: "max_check", Columns: []string{"value"}, Expression: "CHECK ((value <= 100))"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: scores
  value  INTEGER

  CHECK ((value >= 0))
  CHECK ((value <= 100))
`,
		},

		// ==================== Exclusion Constraint Tests ====================
		{
			name: "exclusion constraint is always on separate line",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "room_bookings",
								Columns: []TableColumnSchema{
									{Name: "room_id", Type: "integer"},
									{Name: "during", Type: "tstzrange"},
								},
								Exclusions: []ExclusionConstraint{
									{Name: "room_bookings_excl", Definition: "EXCLUDE USING gist (room_id WITH =, during WITH &&)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: room_bookings
  room_id  INTEGER
  during   TSTZRANGE

  EXCLUDE USING gist (room_id WITH =, during WITH &&)
`,
		},

		// ==================== Index Tests ====================
		{
			name: "regular index on table",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "status", Type: "text"},
								},
								Indexes: []IndexSchema{
									{Name: "users_status_idx", Columns: "status", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  status  TEXT

  INDEX users_status_idx (status)
`,
		},
		{
			name: "unique index on table",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "email", Type: "text"},
								},
								Indexes: []IndexSchema{
									{Name: "users_email_idx", Columns: "email", IsUnique: true},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  email  TEXT

  UNIQUE INDEX users_email_idx (email)
`,
		},
		{
			name: "index with DESC column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "created_at", Type: "timestamp"},
								},
								Indexes: []IndexSchema{
									{Name: "events_created_at_idx", Columns: "created_at DESC", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  created_at  TIMESTAMP

  INDEX events_created_at_idx (created_at DESC)
`,
		},
		{
			name: "index with DESC NULLS LAST",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "created_at", Type: "timestamp"},
								},
								Indexes: []IndexSchema{
									{Name: "events_created_at_idx", Columns: "created_at DESC NULLS LAST", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  created_at  TIMESTAMP

  INDEX events_created_at_idx (created_at DESC NULLS LAST)
`,
		},
		{
			name: "index with ASC NULLS FIRST",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "created_at", Type: "timestamp"},
								},
								Indexes: []IndexSchema{
									{Name: "events_created_at_idx", Columns: "created_at NULLS FIRST", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  created_at  TIMESTAMP

  INDEX events_created_at_idx (created_at NULLS FIRST)
`,
		},
		{
			name: "partial index with WHERE clause",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "products",
								Columns: []TableColumnSchema{
									{Name: "category", Type: "text"},
									{Name: "in_stock", Type: "boolean"},
								},
								Indexes: []IndexSchema{
									{Name: "products_in_stock_idx", Columns: "category", IsUnique: false, WhereClause: "(in_stock = true)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: products
  category  TEXT
  in_stock  BOOLEAN

  INDEX products_in_stock_idx (category) WHERE (in_stock = true)
`,
		},
		{
			name: "expression index",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "documents",
								Columns: []TableColumnSchema{
									{Name: "title", Type: "text"},
								},
								Indexes: []IndexSchema{
									{Name: "documents_lower_title_idx", Columns: "lower((title)::text)", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: documents
  title  TEXT

  INDEX documents_lower_title_idx (lower((title)::text))
`,
		},
		{
			name: "multi-column index",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "documents",
								Columns: []TableColumnSchema{
									{Name: "category", Type: "text"},
									{Name: "created_at", Type: "timestamp"},
								},
								Indexes: []IndexSchema{
									{Name: "documents_cat_created_idx", Columns: "category, created_at DESC", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: documents
  category    TEXT
  created_at  TIMESTAMP

  INDEX documents_cat_created_idx (category, created_at DESC)
`,
		},

		// ==================== View Tests ====================
		{
			name: "view with simple columns",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "active_users",
								Columns: []ViewColumnSchema{
									{Name: "id", Type: "integer"},
									{Name: "email", Type: "text"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: active_users
  id     INTEGER
  email  TEXT
`,
		},
		{
			name: "view column types are uppercased",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "user_view",
								Columns: []ViewColumnSchema{
									{Name: "name", Type: "character varying(255)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: user_view
  name  CHARACTER VARYING(255)
`,
		},
		{
			name:               "view with definition",
			includeDefinitions: true,
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "active_users",
								Columns: []ViewColumnSchema{
									{Name: "id", Type: "integer"},
								},
								Definition: "SELECT id\n   FROM users\n  WHERE active;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: active_users
  id  INTEGER

  AS
    SELECT id
       FROM users
      WHERE active;
`,
		},
		{
			name:               "view with instead-of trigger",
			includeDefinitions: true,
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "active_users",
								Columns: []ViewColumnSchema{
									{Name: "id", Type: "integer"},
								},
								Triggers: []TriggerSchema{
									{Name: "active_users_insert", Timing: "INSTEAD OF", Manipulation: "INSERT", Statement: "EXECUTE FUNCTION active_users_insert_fn()"},
								},
								Definition: "SELECT id\n   FROM users;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: active_users
  id  INTEGER

  TRIGGER active_users_insert INSTEAD OF INSERT EXECUTE FUNCTION active_users_insert_fn()

  AS
    SELECT id
       FROM users;
`,
		},
		// ==================== Partitioned Table Tests ====================
		{
			name: "partitioned table lists its partitions",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "bigint", NotNull: true},
									{Name: "occurred_at", Type: "date", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "events_pk", Columns: []string{"id", "occurred_at"}},
								},
								Partitions: []PartitionInfo{
									{Name: "events_2024", Bound: "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"},
									{Name: "events_2025", Bound: "FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  id           BIGINT NOT NULL
  occurred_at  DATE NOT NULL

  PRIMARY KEY (id, occurred_at)
  PARTITION events_2024 FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')
  PARTITION events_2025 FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')
`,
		},
		{
			name: "partition without bound expression",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "bigint"},
								},
								Partitions: []PartitionInfo{
									{Name: "events_default"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  id  BIGINT

  PARTITION events_default
`,
		},
		{
			name: "partition in a different schema is schema-qualified",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "events",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "bigint"},
								},
								Partitions: []PartitionInfo{
									{Name: "events_2024", Bound: "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"},
									{Name: "events_archive", Schema: "archive", Bound: "FOR VALUES FROM ('2023-01-01') TO ('2024-01-01')"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: events
  id  BIGINT

  PARTITION events_2024 FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')
  PARTITION archive.events_archive FOR VALUES FROM ('2023-01-01') TO ('2024-01-01')
`,
		},
		{
			name:               "materialized view with definition",
			includeDefinitions: true,
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "user_stats",
								Columns: []ViewColumnSchema{
									{Name: "n", Type: "bigint"},
								},
								Indexes: []IndexSchema{
									{Name: "user_stats_n_idx", Columns: "n"},
								},
								Definition: "SELECT count(*) AS n\n   FROM users;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: user_stats
  n  BIGINT

  INDEX user_stats_n_idx (n)

  AS
    SELECT count(*) AS n
       FROM users;
`,
		},
		{
			name: "view definition omitted by default",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "active_users",
								Columns: []ViewColumnSchema{
									{Name: "id", Type: "integer"},
								},
								Definition: "SELECT id\n   FROM users\n  WHERE active;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: active_users
  id  INTEGER
`,
		},

		// ==================== Routine (Function/Procedure) Tests ====================
		{
			name:               "function with body included",
			includeDefinitions: true,
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Functions: []Routine{
							{
								Name:       "add",
								Arguments:  "integer, integer",
								Definition: "CREATE OR REPLACE FUNCTION public.add(a integer, b integer)\n RETURNS integer\nAS $function$ SELECT a + b $function$;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

FUNCTION: add(integer, integer)
  CREATE OR REPLACE FUNCTION public.add(a integer, b integer)
   RETURNS integer
  AS $function$ SELECT a + b $function$;
`,
		},
		{
			name: "function body omitted by default",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Functions: []Routine{
							{
								Name:       "add",
								Arguments:  "integer, integer",
								Definition: "CREATE OR REPLACE FUNCTION public.add(a integer, b integer)\n RETURNS integer\nAS $function$ SELECT a + b $function$;",
							},
						},
						Procedures: []Routine{
							{
								Name:       "do_thing",
								Arguments:  "text",
								Definition: "CREATE OR REPLACE PROCEDURE public.do_thing(t text)\nAS $procedure$ BEGIN END $procedure$;",
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

FUNCTION: add(integer, integer)

PROCEDURE: do_thing(text)
`,
		},

		// ==================== Materialized View Tests ====================
		{
			name: "materialized view with simple columns",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "user_stats",
								Columns: []ViewColumnSchema{
									{Name: "user_id", Type: "integer"},
									{Name: "post_count", Type: "bigint"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: user_stats
  user_id     INTEGER
  post_count  BIGINT
`,
		},
		{
			name: "materialized view with regular index",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "category_stats",
								Columns: []ViewColumnSchema{
									{Name: "category", Type: "text"},
								},
								Indexes: []IndexSchema{
									{Name: "category_stats_idx", Columns: "category", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: category_stats
  category  TEXT

  INDEX category_stats_idx (category)
`,
		},
		{
			name: "materialized view with unique index",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "user_stats",
								Columns: []ViewColumnSchema{
									{Name: "user_id", Type: "integer"},
								},
								Indexes: []IndexSchema{
									{Name: "user_stats_user_id_idx", Columns: "user_id", IsUnique: true},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: user_stats
  user_id  INTEGER

  UNIQUE INDEX user_stats_user_id_idx (user_id)
`,
		},
		{
			name: "materialized view column types are uppercased",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "stats",
								Columns: []ViewColumnSchema{
									{Name: "avg_price", Type: "numeric(10,2)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: stats
  avg_price  NUMERIC(10,2)
`,
		},

		// ==================== Enum Tests ====================
		{
			name: "enum with single value",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Enums: []EnumSchema{
							{Name: "status", Values: []string{"active"}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

ENUM: status
  'active'
`,
		},
		{
			name: "enum with multiple values",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Enums: []EnumSchema{
							{Name: "status", Values: []string{"active", "inactive", "banned"}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

ENUM: status
  'active', 'inactive', 'banned'
`,
		},

		// ==================== Blank Line Separator Tests ====================
		{
			name: "no blank line when table has no extra constraints or indexes",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer"},
									{Name: "name", Type: "text"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "users_pkey", Columns: []string{"id"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id    INTEGER PRIMARY KEY
  name  TEXT
`,
		},
		{
			name: "blank line before multi-column constraint",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "items",
								Columns: []TableColumnSchema{
									{Name: "a", Type: "integer"},
									{Name: "b", Type: "integer"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "items_pkey", Columns: []string{"a", "b"}},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: items
  a  INTEGER
  b  INTEGER

  PRIMARY KEY (a, b)
`,
		},
		{
			name: "blank line before indexes",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "email", Type: "text"},
								},
								Indexes: []IndexSchema{
									{Name: "users_email_idx", Columns: "email", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  email  TEXT

  INDEX users_email_idx (email)
`,
		},
		{
			name: "no blank line in materialized view without indexes",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{
								Name: "stats",
								Columns: []ViewColumnSchema{
									{Name: "count", Type: "bigint"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: stats
  count  BIGINT
`,
		},

		// ==================== Column Alignment Tests ====================
		{
			name: "columns are aligned by name length in tables",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer"},
									{Name: "longer_name", Type: "text"},
									{Name: "x", Type: "boolean"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  id           INTEGER
  longer_name  TEXT
  x            BOOLEAN
`,
		},
		{
			name: "columns are aligned by name length in views",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{
								Name: "my_view",
								Columns: []ViewColumnSchema{
									{Name: "short", Type: "integer"},
									{Name: "very_long_column_name", Type: "text"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: my_view
  short                  INTEGER
  very_long_column_name  TEXT
`,
		},

		// ==================== Combined Inline Constraints Test ====================
		{
			name: "multiple inline constraints on same column",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "email", Type: "text", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintUnique, Name: "users_email_key", Columns: []string{"email"}},
								},
								Checks: []CheckConstraint{
									{Name: "email_check", Columns: []string{"email"}, Expression: "CHECK ((email ~~ '%@%'))"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: users
  email  TEXT NOT NULL UNIQUE CHECK ((email ~~ '%@%'))
`,
		},

		// ==================== Full Schema Integration Tests ====================
		{
			name: "multiple tables are output in order provided",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{Name: "apple", Columns: []TableColumnSchema{{Name: "id", Type: "integer"}}},
							{Name: "mango", Columns: []TableColumnSchema{{Name: "id", Type: "integer"}}},
							{Name: "zebra", Columns: []TableColumnSchema{{Name: "id", Type: "integer"}}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: apple
  id  INTEGER

TABLE: mango
  id  INTEGER

TABLE: zebra
  id  INTEGER
`,
		},
		{
			name: "multiple views are output in order provided",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Views: []ViewSchema{
							{Name: "a_view", Columns: []ViewColumnSchema{{Name: "id", Type: "integer"}}},
							{Name: "z_view", Columns: []ViewColumnSchema{{Name: "id", Type: "integer"}}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

VIEW: a_view
  id  INTEGER

VIEW: z_view
  id  INTEGER
`,
		},
		{
			name: "multiple materialized views are output in order provided",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						MaterializedViews: []ViewSchema{
							{Name: "a_stats", Columns: []ViewColumnSchema{{Name: "count", Type: "bigint"}}},
							{Name: "z_stats", Columns: []ViewColumnSchema{{Name: "count", Type: "bigint"}}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

MATERIALIZED VIEW: a_stats
  count  BIGINT

MATERIALIZED VIEW: z_stats
  count  BIGINT
`,
		},
		{
			name: "multiple enums are output in order provided",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Enums: []EnumSchema{
							{Name: "a_type", Values: []string{"b"}},
							{Name: "z_type", Values: []string{"a"}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

ENUM: a_type
  'b'

ENUM: z_type
  'a'
`,
		},
		{
			name: "full schema with all object types in correct order",
			schema: &DatabaseSchema{
				ID:   "abc123",
				Name: "myapp",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "users",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IsSerial: true, NotNull: true},
									{Name: "email", Type: "text", NotNull: true},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "users_pkey", Columns: []string{"id"}},
									{Type: ConstraintUnique, Name: "users_email_key", Columns: []string{"email"}},
								},
							},
						},
						Views: []ViewSchema{
							{
								Name: "active_users",
								Columns: []ViewColumnSchema{
									{Name: "id", Type: "integer"},
									{Name: "email", Type: "text"},
								},
							},
						},
						MaterializedViews: []ViewSchema{
							{
								Name: "user_stats",
								Columns: []ViewColumnSchema{
									{Name: "user_id", Type: "integer"},
									{Name: "count", Type: "bigint"},
								},
								Indexes: []IndexSchema{
									{Name: "user_stats_user_id_idx", Columns: "user_id", IsUnique: true},
								},
							},
						},
						Enums: []EnumSchema{
							{Name: "status", Values: []string{"active", "inactive"}},
						},
					},
				},
			},
			expected: `DATABASE: myapp (abc123)

SCHEMA: public

TABLE: users
  id     SERIAL PRIMARY KEY
  email  TEXT NOT NULL UNIQUE

VIEW: active_users
  id     INTEGER
  email  TEXT

MATERIALIZED VIEW: user_stats
  user_id  INTEGER
  count    BIGINT

  UNIQUE INDEX user_stats_user_id_idx (user_id)

ENUM: status
  'active', 'inactive'
`,
		},
		{
			name: "complex table with all constraint types",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "orders",
								Columns: []TableColumnSchema{
									{Name: "id", Type: "integer", IsSerial: true, NotNull: true},
									{Name: "user_id", Type: "integer", NotNull: true},
									{Name: "status", Type: "text", NotNull: true, Default: "'pending'"},
									{Name: "total", Type: "numeric(10,2)"},
									{Name: "created_at", Type: "timestamp", Default: "now()"},
								},
								Constraints: []TableConstraint{
									{Type: ConstraintPrimaryKey, Name: "orders_pkey", Columns: []string{"id"}},
									{Type: ConstraintForeignKey, Name: "orders_user_fkey", Columns: []string{"user_id"}, RefTable: "users", RefColumns: []string{"id"}},
								},
								Checks: []CheckConstraint{
									{Name: "orders_total_check", Columns: []string{"total"}, Expression: "CHECK ((total >= 0))"},
								},
								Indexes: []IndexSchema{
									{Name: "orders_user_id_idx", Columns: "user_id", IsUnique: false},
									{Name: "orders_created_at_idx", Columns: "created_at DESC", IsUnique: false},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: orders
  id          SERIAL PRIMARY KEY
  user_id     INTEGER NOT NULL REFERENCES users(id)
  status      TEXT NOT NULL DEFAULT 'pending'
  total       NUMERIC(10,2) CHECK ((total >= 0))
  created_at  TIMESTAMP DEFAULT now()

  INDEX orders_user_id_idx (user_id)
  INDEX orders_created_at_idx (created_at DESC)
`,
		},

		// ==================== Edge Cases ====================
		{
			name: "empty database with no objects",
			schema: &DatabaseSchema{
				ID:   "empty123",
				Name: "emptydb",
			},
			expected: "DATABASE: emptydb (empty123)\n",
		},
		{
			name: "table with no columns",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{Name: "empty_table", Columns: []TableColumnSchema{}},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: empty_table
`,
		},
		{
			name: "check constraint with no columns",
			schema: &DatabaseSchema{
				ID:   "test123",
				Name: "testdb",
				Schemas: []NamespacedSchema{
					{
						Name: "public",
						Tables: []TableSchema{
							{
								Name: "config",
								Columns: []TableColumnSchema{
									{Name: "value", Type: "integer"},
								},
								Checks: []CheckConstraint{
									{Name: "config_check", Columns: []string{}, Expression: "CHECK (true)"},
								},
							},
						},
					},
				},
			},
			expected: `DATABASE: testdb (test123)

SCHEMA: public

TABLE: config
  value  INTEGER

  CHECK (true)
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := FormatSchema(tt.schema, tt.includeDefinitions)
			if diff := cmp.Diff(tt.expected, result); diff != "" {
				t.Errorf("FormatSchema() mismatch (-expected +got):\n%s", diff)
			}
		})
	}
}

func TestSchemaNotFoundError(t *testing.T) {
	tests := []struct {
		name     string
		err      *SchemaNotFoundError
		expected string
	}{
		{
			name:     "with available schemas",
			err:      &SchemaNotFoundError{Schema: "typo", Available: []string{"public", "sales"}},
			expected: `schema "typo" not found; available schemas: public, sales`,
		},
		{
			name:     "no available schemas",
			err:      &SchemaNotFoundError{Schema: "typo"},
			expected: `schema "typo" not found`,
		},
		{
			name:     "listing failed",
			err:      &SchemaNotFoundError{Schema: "typo", ListErr: errors.New("boom")},
			expected: `schema "typo" not found (failed to list available schemas: boom)`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if diff := cmp.Diff(tt.expected, tt.err.Error()); diff != "" {
				t.Errorf("Error() mismatch (-expected +got):\n%s", diff)
			}
			// ListErr should be unwrappable for errors.Is/As chains.
			if tt.err.ListErr != nil && !errors.Is(tt.err, tt.err.ListErr) {
				t.Errorf("errors.Is did not match wrapped ListErr")
			}
		})
	}
}
