name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache: true

      - name: ShellCheck
        run: shellcheck scripts/install.sh

      - name: Build web bundle
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/build-web.sh

      - name: Mod
        run: go mod tidy -diff

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Fix
        run: go fix -omitzero=false -diff ./...

      - name: Staticcheck
        run: go tool staticcheck ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out -coverpkg=./... ./...

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o=coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage.html
          path: coverage.html
